### ISSUE TITLE
Request - not able to not fill out an attribute in identifications

### ISSUE THREAD

**Issue by happiah-madson** [ArctosDB/arctos#8332]
Help us understand your request (check below):
- [ ] search or data request (help with SQL or provide the specific fields you are trying to retrieve for your collection)
- [ ] add a new Github user to the Arctos Users team
- [ ] a new barcode series
- [ ] a new term for data entry or management 
- [ ] a change or new report or label
- [ ] update to an Agent (split, merge, or other type of change)
- [ ] bulkload changes (to Agents, Identifiers, etc that are not already available as a bulkloading tool)
- [ ] new feature or otherwise a good idea to make Arctos even better
- [ ] quarantine taxon name and suggested replacement (please supply links)
- [x] other

**Describe what you're trying to do** 
I was adding an identification to several records, and was adding attributes, when I decided oh no! I've added 1 too many attributes. Despite making the attribute blank, the form requested that I fill out the field before allowing me to add the identification. Because I didn't want to...I had to reload the page and start over. This is so minor, but it would have been delightful if I didn't have to do that. (Was it throwing a fit b/c there was still a determiner and date in that row?)

![Screen Shot 2024-11-25 at 9 46 46 AM](https://github.com/user-attachments/assets/1cb0dba7-3aef-4d2c-8e15-e0a16dcc749b)

@dustymc

**Comment by mkoo** [comment]
>>Was it throwing a fit b/c there was still a determiner and date in that row?

Yes! this happens to me too -- like a crime scene cleaner, try to get rid of all evidence of an attempt to add a row.

**Comment by mkoo** [comment]
resolved
