### ISSUE TITLE
Help needed in Arctos: things stuck in the bulkloader?

### ISSUE THREAD

**Issue by happiah-madson** [ArctosDB/arctos#8335]
# Tell us what you are trying to do 
load positions via the loadContainerToPosition tool https://arctos.database.museum/loaders/loadContainerToPosition.cfm

# What are relevant pages in Arctos
**Provide a link to or a description of the page where you need help.**
students have had data marked as autoload in the bulkloader over the weekend...which seems a little long?

@dustymc

**Comment by dustymc** [comment]
https://arctos.database.museum/info/component_loader_status.cfm will tell you when things should happen. There should be some comment at the top if there's a priority (there's not), otherwise feel free to reorder. There's no set "too long" time, things can run indefinitely.

**Comment by happiah-madson** [comment]
![Screen Shot 2024-11-25 at 3 04 15 PM](https://github.com/user-attachments/assets/b23e08dd-ab73-4755-be87-c4423afb8d56)

Can you point me to somewhere that defines the columns? In the text above, it says that what is in the table is minutes. Does that mean that RPM, Autoloads, Pendings, Runtime, and Cumulitive are all minutes for that given tool?

On the right side, I understand "username", but does "recs" = records? So in this picture does the first user have 525 records in the tool but none of them are have the autoload status, so ostensibly are not being loaded?

**Comment by dustymc** [comment]
>point me to somewhere that defines

No.... (So Issue please! I try not to write things which don't all make perfect intuitive sense - to me, not easy to guess where that stops for everyone else....)

RPM==records per minute
Autoloads, Pendings==recordcount
 Runtime, and Cumulitive==minutes

>ostensibly

Don't think there's that much mystery here, but maybe....

>none of them are have the autoload status

so they're not doing anything (except hanging around waiting to become problematic at the next yearly cleanup, which makes me think maybe that should be monthly cleanups...) / take zero time to process.

The first row that is doing something is...
<img width="573" alt="Screenshot 2024-11-25 at 12 16 02" src="https://github.com/user-attachments/assets/4b728239-b170-481b-91a4-f750167d2086">

which processes 5K records and 10 per minute == 500 minutes

That gets added up all down the page....

<img width="545" alt="Screenshot 2024-11-25 at 12 16 52" src="https://github.com/user-attachments/assets/2d720aac-bbd8-4513-9b2c-34909dace240">

... which needs a little over 600 minutes to finish from whenever I loaded it - IF nobody changes anything, and  someone loading a million records that run at one per minute in front of you is always possible, so please use the comments if you have a priority!

**Comment by happiah-madson** [comment]
Ah, makes mucchhhhhhh more sense. I couldn't quite figure out why tools with 0 or very few records had cumulative minutes in the hundreds...

>No.... (So Issue please! I try not to write things which don't all make perfect intuitive sense - to me, not easy to guess where that stops for everyone else....)

as _specifically requested_: https://github.com/ArctosDB/arctos/issues/8336
