### ISSUE TITLE
Date Entry Lacking Locality (originally posted elsewhere)

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#8337]
From @ehalverson26 
> I recently entered some records indiviudally into our herp database, however, upon inspection it seems that none of the locality and date data (maybe more?) uploaded.
> 
> The records in question are UWZM:Herp 23157-23163 and 23189-23192. I also tried adding the locality manually after I realized they were not there by "creating a new specimen/event" but that did not seem to work either.
> 
> Other than these records, I have only bulkloaded records so I am not sure where to go from there.

HI @ehalverson26 I think we could help you if you showed me in a demo or if you specify the exact steps.

**Comment by Jegelewicz** [comment]
My guess is that the record event type was left NULL and so no locality information was loaded.

https://handbook.arctosdb.org/how_to/How-to-Enter-Data-for-a-Single-Record.html#place-and-time

> NONE of the information entered in these sections will save if record_event_type is blank.
Record-Event

**Comment by ehalverson26** [comment]
@Jegelewicz  Yes. That was definitely the problem. Thank you!

**Comment by ehalverson26** [comment]
@Jegelewicz Yes. That was definitely the problem. Thank you!
