### ISSUE TITLE
Arctos Connectivity issue- 11/26/2024 at 1:58pm CT

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#8342]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time (**please add time zone from which you are reporting**) outage discovered:
 - Describe the outage (Arctos down or only some part not working?):

## Planned Outage
 - Date and time outage will begin:
 - Expected duration of outage:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [ ] Pin this issue
- [ ] Banner updated @mkoo
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by lin-fred** [comment]
Yeah it's down for me too

**Comment by dustymc** [comment]
Definitely not down, what are the symptoms you're experiencing?

**Comment by mkoo** [comment]
Fine in California!
Do you have any errors?

**Comment by lin-fred** [comment]
It was just spinning in the browser. Didn't get an error. 

It is fine for me now

**Comment by lin-fred** [comment]
![Screenshot_20241126-133732.png](https://github.com/user-attachments/assets/b9cb3368-5f82-4ccc-bcb7-b32599e93554)

**Comment by campmlc** [comment]
I'm getting 503 error as well, after slow spinning and no response.

**Comment by wellerjes** [comment]
Same; when I first posted the issue it was just spinning. Came back up. but was very slow. Now I'm getting the 503 error.

**Comment by mkoo** [comment]
server errors-- (is it those sql queries this morning?) can you give Arctos a kick in the pants please @dustymc

**Comment by dustymc** [comment]
I've rebooted but waiting for some database things to clear before bringing the front end back up. I will do that as soon as I safely can.

**Comment by lin-fred** [comment]
Thanks Dusty!

**Comment by dustymc** [comment]
Arctos is now available.

**Comment by acdoll** [comment]
Thanks @dustymc !!!
