### ISSUE TITLE
Arctos Errors Discussion

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#836]
"We need better errors" came up often at the Sevilleta Summit. I agree, and it's something we've been working on through documentation, better forms, and "pre-checks" for - well, forever.

I found this in my inbox:

> The first couple worked fine. I clicked 'delete' and then save and it worked. On the 3rd and 4th it doesn't work (i stopped trying). I click delete and when I click save I get a weird pop up in the upper left of the screen that says 'please fill out this field' (see attached screen shot). And it won't save my deletion.

I've used HTML5 in this form to prevent some sort of common error at the browser level; you'll get a nice red "fill this in" (or "this needs to be a number" etc.) message BEFORE you submit the form if you encounter whatever situation inspired this check. It looks like the HTML5 "standard" (it's a "loose" standard) is evolving (probably something about validation and visibility - or perhaps there's something unexpected about these particular records), leading to a cryptic problem with no obvious-to-the-user solution.

It's also important to note that the validation is BEFORE submit; these errors occur only in the browser, and I can only know there's a problem when I'm notified of it.

The raw Oracle errors may be a difficult to read, but:

* They (almost) always contain enough information that Google can lead a knowledgeable user (eg, one with access to the "table browser" tool) to an actionable solution,
* They are generated by exactly one entity (vs. a user's combination of browser/OS/extensions/etc. all interacting to interpret HTML5),
* They remain consistent across all interactions with the database (single and multi-specimen forms, bulkloaders, SQL command line, etc.) 
* They can change only when WE (vs. users) upgrade something.
* They end up in log files and alerts

Attempting to interfere in the error process always introduces complexity, and complexity always has potential failure points.

I intend to upgrade the code causing the problem, then check the site code for anything similar (and see #732, which might accomplish the initial goal across Arctos without introducing this particular point of failure).  I think this particular code is worth maintaining, I'd just like the AWG to better understand the costs of manipulating the native error handling process.

Discuss, please. (And maybe use the comments of this Issue to suggest specific problematic errors which need better handling.)

@DerekSikes

**Comment by dustymc** [comment]
problem fixed and patched in, leaving this open as a general wishlist/base of discussions

**Comment by mkoo** [comment]
AWG 2016-08-01: new page on wiki site where community can copy/paste their Oracle errors and how it was resolved. CAll it the "How to Troubleshoot Arctos Errors"
