### ISSUE TITLE
Help needed in Arctos- requesting url link for organism ID at GBIF

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#8360]
# Tell us what you are trying to do 
We currently supply Organism ID to GBIF to show all related records from a single individual. They display this ID prominently at the top of their record page, including the number of occurrences carrying that ID. But the url displayed is not live, with no active link to the Arctos Entity record. 
This is relevant to NSF funded ZooMu project with several Arctos collaborators. One of the challenges faced by many CMSs is how to deal with multiple occurrence records from the same individual, for example repeat blood and serum samples taken from the same zoo animal over its lifetime. Arctos has already come up with a solution for this by assigning Organism ID as a linking value, with all occurrences displayed in the Arctos Entity dashboard reached by the url. GBIF has made the changes needed to display this. We just need the Entity organism ID url to be live. What do we need to do to get that corrected? Who to contact? 

# What are relevant pages in Arctos
https://arctos.database.museum/guid/Arctos:Entity:250
https://www.gbif.org/occurrence/3125629326

**Comment by Jegelewicz** [comment]
@campmlc I think the easiest thing would be to ask GBIF to make those links live.

**Comment by campmlc** [comment]
@dbloom

**Comment by Jegelewicz** [comment]
Just post an issue in their forum - https://discourse.gbif.org/

**Comment by mkoo** [comment]
@campmlc Mariel, those are the right forums for your issue (thanks Teresa)-- I'm closing here and letting you take it up with GBIF
