### ISSUE TITLE
github wiki is making me crazy

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#837]
I wrote parts of https://github.com/ArctosDB/arctos/wiki/How-to-make-Arctos-work-for-you%3A-Create-an-Issue a while back, and have sent it out in lots of emails etc as https://github.com/ArctosDB/arctos/wiki/Issues:-How-To. The URL changed, which causes the old page to disappear (at least I can't find it), and the new page has lost the old edit history. (I think there was also an intermediate page [or several??] from @amgunderson in there, but I can find no evidence of that now.) That is, changing a wiki page title seems to effectively destroy the old page, create a new page (using the old contents), and break all references to the old page.

Is there any way to maintain stable URLs in github wiki? (Google isn't being helpful.) If not, we need to do SOMETHING - link only to the wiki itself (instead of eg, the Identification how-tos from the Identification forms in Arctos - seems painful), or build (ok) and maintain (eek!) a map/redirect service somewhere, or create a policy of never changing a title (dicey...), or ?????????????, OR we need to find a different platform for documentation.

 @mkoo, @dbloom, @ccicero, ??

**Comment by dustymc** [comment]
blocking #829

**Comment by mkoo** [comment]
ok, I'm going to say this is the wrong way to go about this one-- how about a real set of Pages? Github lets you start a website in no time at all (via gh-pages branch). But maybe I need to back up here. I see now two spots for wiki documentation (the wiki on arctos repo-- https://github.com/ArctosDB/arctos/wiki and new one you guys created this week)
 - what's the diff?
 - I see all your pages (33 of 'em) that you made @dustymc so are any of those missing? they just may not be linked
 - urls are persistent 
 - so what's the purpose of having docs here in two wikis and wordpress?

**Comment by ccicero** [comment]
Dusty - As we discussed, we're moving all documenation to https://github.com/ArctosDB/documentation-wiki/wiki

We need to set rules for how to title wiki pages so that there is consistency in format and you don't get funky characters in the url.  I edited the instructions for creating documentation per what we discussed: https://github.com/ArctosDB/documentation-wiki/wiki/How-to-Create-or-Edit-Content-on-the-Arctos-Wiki

That page is not one that has been moved, so I'm not sure that the URL has changed (?). However, I do need to move that to the new wiki site and will probably rename the page to get rid of the funky characters. 

I wouldn't worry about the emails, we can (and will need to) notify people about where to view documentation, submit issues, how to create github account, etc.

Where do you have this linked from in Arctos? Can you hold off on making changes until we clean some things up this week and then we can fix the URLs in Arctos, notify users, and add the github link to the Arctos operator email.

**Comment by ccicero** [comment]
Just hold on! We are in process of organizing documentation based on what we discussed at the workshop, and will get rid of the pages on the /arctos/wiki site and ONLY have documentation on the /documentation-wiki/wiki site.

WordPress will link to the documentation, but have a lot of other changes to the site based on a lot of great discussion.

So just be patient for a week while we organize the documentation, meanwhile Michelle, let us know when the wordpress site is in AWS and we can start making changes there.

**Comment by dustymc** [comment]
>how about a real set of Pages?

I have no idea what that means....

>we're moving all documenation to https://github.com/ArctosDB/documentation-wiki/wiki

Yea I somehow missed that....

>I see all your pages (33 of 'em) that you made @dustymc so are any of those missing? they just may not be linked

where? What does https://github.com/ArctosDB/arctos/wiki/Issues:-How-To do for you? For me, "create a new page" (with the title filled in).

>urls are persistent 

Not for me! (And I really hope I'm wrong on that...)

>so what's the purpose of having docs here in two wikis 

See @ccicero - I guess we're moving!

>and wordpress?

My understanding is that we're moving some/most stuff from there, and so we'll have to revise the links to there. (Or perhaps that could be our redirect service???? http://arctosdb.org/documentation/catalog/#collection bounces to github/whatever/same_information????)

>I wouldn't worry about the emails, we can (and will need to) notify people about where to view documentation, submit issues, how to create github account, etc.

Can you comment on #829 then? YOU (or any given Curator) may not need that direct link, but (as we discussed) I'm constantly getting questions from eg, grad students who are obviously not "in the loop," and this will guarantee that they've at least had the chance to learn how to get involved.

>Where do you have this linked from in Arctos? 

There are hundreds or thousands of links to documentation from Arctos. Click anything from specimensearch, then "more information" in the green popup, for example.

>Can you hold off on making changes

Yes, no problem - I'm not trying to change anything at this time, I was just trying to use a bookmark. I also can't un-send the emails that have gone out over the past several months (including https://groups.google.com/forum/#!searchin/Arctos/github/arctos/tQk3LcT0Mlc/XMbzDyroBQAJ). That probably isn't completely critical, but it's not clear to me how maintaining stability under GH's (otherwise pretty awesome) wiki is going to work, and I REALLY don't want broken links to (or not to..) documentation every time someone makes some seemingly-innocuous change to a page title.

**Comment by dustymc** [comment]
Somehow seems to work despite the generated URLs, closing.
