### ISSUE TITLE
Bug Report: Issue with file upload for Bulk tools

### ISSUE THREAD

**Issue by KatherineLAnderson** [ArctosDB/arctos#8371]
**Describe the bug**
I select a file to upload on the load csv page, and when I hit "Upload this file" the browser returns to the starting page but the file was not imported/data are not populating the table for review.

This is happening on and off in various places.

Bulk edit parts
https://arctos.database.museum/loaders/bulk_edit_parts.cfm
File: [December Existing Part Update_KLA.csv](https://github.com/user-attachments/files/18137867/December.Existing.Part.Update_KLA.csv)

Identification bulkloader
https://arctos.database.museum/loaders/BulkloadIdentification.cfm
File: [December Identification update_KLA.csv](https://github.com/user-attachments/files/18137874/December.Identification.update_KLA.csv)
This uploaded a file, then I realized there was an error and deleted it from the pending table. I fixed the error and on attempt to reupload, it's not uploading.

Also just happened with the part attribute uploader, which worked 5 minutes ago, but not now.

**To Reproduce**
1. Go to the links above
2. Click on 'load csv'
3. Click browse. Choose the file to upload and hit upload.
4. See it redirect you to the original page with no data in the table

**Screenshots**

**Data**
Files above!

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Firefox
 - Version

**Additional context**
n/a

**Comment by KatherineLAnderson** [comment]
Maybe fixed? I managed to get all the files to import.

**Comment by KatherineLAnderson** [comment]
It worked in safari. I'll see if I can install any updates to my system or browser...

**Comment by mkoo** [comment]
Great to hear that @KatherineLAnderson I am tentatively closing since there's nothing actionable here for Arctos
