### ISSUE TITLE
Help needed in Arctos: error code

### ISSUE THREAD

**Issue by happiah-madson** [ArctosDB/arctos#8374]
# Tell us what you are trying to do 
Bulk upload records

# What are relevant pages in Arctos
**Provide a link to or a description of the page where you need help.**

Getting this error: column "valid_catalog_term_fg" does not exist
[BulkPendingData(1).csv](https://github.com/user-attachments/files/18168404/BulkPendingData.1.csv)

**Comment by dustymc** [comment]
I loaded https://arctos.database.museum/guid/OGL:Genomic:40725 looking for the sneaky bug - fixed, thanks!

**Comment by happiah-madson** [comment]
thank you!
