### ISSUE TITLE
Request - more part attributes in the bulkloader?

### ISSUE THREAD

**Issue by happiah-madson** [ArctosDB/arctos#8375]
Help us understand your request (check below):
- [ ] search or data request (help with SQL or provide the specific fields you are trying to retrieve for your collection)
- [ ] add a new Github user to the Arctos Users team
- [ ] a new barcode series
- [ ] a new term for data entry or management 
- [ ] a change or new report or label
- [ ] update to an Agent (split, merge, or other type of change)
- [x] bulkload changes (to Agents, Identifiers, etc that are not already available as a bulkloading tool)
- [ ] new feature or otherwise a good idea to make Arctos even better
- [ ] quarantine taxon name and suggested replacement (please supply links)
- [ ] other

**Describe what you're trying to do** 
Any chance that we could increase the number of attributes for parts in the bulkloader to 11?

**Comment by dustymc** [comment]
Please clarify, to which bulkloader does this request apply?

Possible dup of https://github.com/ArctosDB/arctos/issues/7590 (which I just noticed because of the funky milestone, sorry!)
