### ISSUE TITLE
Moving Specimen Results Row Count display

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#838]
Move Row Count Display Tool from bottom of Specimen Results display to the top of page.

![screenshot 2016-02-22 13 17 15](https://cloud.githubusercontent.com/assets/14808196/13231381/d196baa6-d966-11e5-897f-c26581261126.png)

**Comment by dustymc** [comment]
A preliminary investigation suggests the placement of the page tools widget isn't controllable; fulfilling this issue would be a ~couple weeks work (replacing the jtables library with something else everywhere it's used) after selecting a new UI.
