### ISSUE TITLE
Help needed in Arctos: Media thumbnails not showing up

### ISSUE THREAD

**Issue by DellaCHall** [ArctosDB/arctos#8388]
# Tell us what you are trying to do 
Media thumbnails that I uploaded are not showing up, many months after I uploaded the media.

# What are relevant pages in Arctos
[Here are the ones I am talking about](https://arctos.database.museum/search.cfm?guid_prefix=UAM%3AArt&accn_number=2023&sp=preset_art)

I trained a student to upload media and those thumbnails are showing up fine...What am I doing wrong?

**Comment by AJLinn** [comment]
This happens to me ALL the time. You can usually fix this in one of two ways.

1. If you come across a single record where the thumbnail isn't showing up at the search results page, go into the catalog record and click on the "request cache refresh". Your thumbnail preview should show up after that (I haven't tested to see how long this takes).
<img width="497" alt="Screenshot 2024-12-19 at 4 39 13 PM" src="https://github.com/user-attachments/assets/07196dae-e29c-4b1f-a52a-9721a598d582" />

2. If you have a whole bunch of records in your search results with only the preview Arctos bear saying there's "media available" you can go into the Tools menu and "Request Flat Refresh".
<img width="566" alt="Screenshot 2024-12-19 at 4 40 08 PM" src="https://github.com/user-attachments/assets/0096ddb3-3b11-4814-b461-02dd28d8b41a" />

Should fix you up sooner than later... @dustymc might have an answer as to how long it takes.

**Comment by DellaCHall** [comment]
Like magic! Thank you @AJLinn !
