### ISSUE TITLE
Bug Report - publication not found but it exists

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#8389]
**Describe the bug**
A clear and concise description of the encountered error.

Trying to bulkload citations, getting error I shouldn't get

https://arctos.database.museum/loaders/BulkloadCitations.cfm

publication notfound

PUBLICATIONID
10012278

https://arctos.database.museum/SpecimenUsage.cfm?action=search&publication_id=10012278

[bulkloader_citation(9).csv](https://github.com/user-attachments/files/18204230/bulkloader_citation.9.csv)

**Comment by DerekSikes** [comment]
@dustymc I'd like to get these citations loaded

**Comment by dustymc** [comment]
`` "https://arctos.database.museum/publication/10009052". Either publicationID or doi is required. ``

Use the full identifier.

**Comment by DerekSikes** [comment]
Oh, another change to this? We can't use the ID 10012278 alone, we have to use the URL string:
https://arctos.database.museum/publication/10012278
Maybe edit the documentation page to add the words "full URL string" since so many of us have been trained for well over a decade now with use of just the ID itself. I read the current documentation and figured that the URL in the help info there was just to show folks where to get the ID number.
Thanks
