### ISSUE TITLE
Query or queries syntax error

### ISSUE THREAD

**Issue by jldunnum** [ArctosDB/arctos#840]
http://arctos.database.museum/guid/MSB:Mamm:265331.  Can't add a part to this specimen.

	An error occurred while processing this page! 
Error Executing Database Query. 

Query Of Queries syntax error.
Encountered "sampled_from_obj_id = order. Incorrect conditional expression, Expected one of [like|null|between|in|comparison] condition,
This message has been logged. Please contact us with any information that might help us to resolve this problem.

**Comment by dustymc** [comment]
fix is patched in
