### ISSUE TITLE
this is a test from a user without any permissions at all

### ISSUE THREAD

**Issue by ijustmadethisup** [ArctosDB/arctos#841]
@dustymc @ccicero

**Comment by ijustmadethisup** [comment]
<img width="420" alt="screen shot 2016-02-24 at 4 18 29 pm" src="https://cloud.githubusercontent.com/assets/17463422/13305724/4dd829b8-db12-11e5-9a7c-75cbda04420c.png">

Random users can file issue, comment on them, and close them, but can't set labels/milestones/assignee

**Comment by ijustmadethisup** [comment]
Now I'm a member but I still don't have any labels etc. and I can't edit or add to the wiki

**Comment by campmlc** [comment]
So you need to be an owner to those things, unfortunately.

**Comment by ijustmadethisup** [comment]
You also need to not be banned from github to post on the wiki....

Unbanned, our "member" user can post and edit @ https://github.com/ArctosDB/documentation-wiki/wiki/test---delete-at-will
