### ISSUE TITLE
coll event coordinates vs locality coordinates

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#843]
update events per email from DSS

**Comment by dustymc** [comment]
Awaiting response re: shared events

**Comment by campmlc** [comment]
Is this something the working group needs to provide input on?

**Comment by dustymc** [comment]
No, this is a "note to self"  - I'm just trying to be organized. (Maybe we need some sort of marker for that??)

**Comment by campmlc** [comment]
I saw you had only assigned yourself, but was confused by language.  But
maybe we could create some sort of "working group" group assignment - or
some other means to indicate the group needs to respond.

**Comment by dustymc** [comment]
I try to use the "[Needs Discussion](https://github.com/ArctosDB/arctos/milestones/Needs%20Discussion)" Milestone for that.

**Comment by campmlc** [comment]
That works.
