### ISSUE TITLE
Shipping Label report not working from Arctos

### ISSUE THREAD

**Issue by atrox10** [ArctosDB/arctos#845]
@dustymc 
Dusty - shipping label report printout is not working from loans. We just tried for loan MVZ.Herp.2016.8268.Herp and we are getting this error:

An error occurred while processing this page! 
The report CFR file /usr/local/httpd/htdocs/wwwarctos/Reports/templates/ship_label.cfr could not be found.

**Comment by dustymc** [comment]
It looks like someone copied/renamed/deleted that or something of the sort. I restored it. Do you use both shipping_label (what was just resurrected) and MVZ_Ship_Label? If not, can you delete one of them (and anything else of yours that you're not using)?

Thx-D

**Comment by atrox10** [comment]
I guess Carla and others use the MVZ one, my students and I always just use
the shipping one from the front page of the loan.

On Thu, Feb 25, 2016 at 3:37 PM, dustymc <notifications@github.com> wrote:

> It looks like someone copied/renamed/deleted that or something of the
> sort. I restored it. Do you use both shipping_label (what was just
> resurrected) and MVZ_Ship_Label? If not, can you delete one of them (and
> anything else of yours that you're not using)?
>
> Thx-D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ArctosDB/arctos/issues/845#issuecomment-189035819>.
>



-- 
Carol L. Spencer, Ph.D.
Staff Curator of Herpetology & Researcher
Museum of Vertebrate Zoology
3101 Valley Life Sciences Building
University of California, Berkeley, CA, USA 94720-3160
atrox10@gmail.com  and  atrox@berkeley.edu
510-643-5778 /FAX: 510-643-8238

http://www.herpnet.org
http://mvz.berkeley.edu/
http://www.vertnet.org

**Comment by AJLinn** [comment]
I think this same problem has occurred. I'm getting this error:

<img width="943" alt="screen shot 2019-02-01 at 4 13 49 pm" src="https://user-images.githubusercontent.com/17605945/52157625-f3b30600-263c-11e9-95ab-2bae67b6f90e.png">

I tested it last week and it seemed to work fine. Now I'm getting an error. Did I do something wrong???

**Comment by dustymc** [comment]
I'd guess someone's clicked the wrong button (again?), but I don't really know what happened. There is some automated maintenance that could have somehow got sideways. This thing..

<img width="650" alt="screen shot 2019-02-02 at 7 06 21 am" src="https://user-images.githubusercontent.com/5720791/52165714-15ea6980-26b9-11e9-969b-b003987e4a0f.png">

...should not be ignored - I don't think we have backups of that machine at all, and often reports are changing faster than backups would anyway.

I'm happy to talk about a different strategy if the current situation isn't working.

I had a fairly old template of the same name on my computer, so I cloned the MVZ ship label and used that to hopefully-recreate.

[ship_label.cfr.zip](https://github.com/ArctosDB/arctos/files/2824524/ship_label.cfr.zip)

**Comment by Jegelewicz** [comment]
The list of reports is already out of control. We need to figure out a better way to organize them...That might help.

**Comment by mkoo** [comment]
AWG 3/7/2019: Carol confirms form is working.
