### ISSUE TITLE
find a better place for wiki images

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#846]
The wiki images are currently going to https://github.com/ArctosDB/arctos/tree/master/tutorial_images for some reason. That folder is part of the code; I have to drag the images around with the code, and they're taking up space on the webservers. We have to find a better place for them and move the existing to it - maybe the repository in https://github.com/ArctosDB/documentation-wiki or something.

**Comment by ebraker** [comment]
Wherever you relocate them should be fine. I don't believe the current location is "meaningful" other than we need a spot for the tutorial images folder to go on github as the wiki requires that all images have a url. I've been adding images today - apologies for clogging up webserver space!

**Comment by campmlc** [comment]
Yes, we put the images where they are because at the time there was no
other repository, but now that we have the documentation-wiki repository
the file should be moved there. However, we need to make sure that moving
the image folder will not break the links to the documents in the wiki that
are using those images. The documents are linking to the image url.

**Comment by ebraker** [comment]
It doesn't appear that the tutorial folder can be redirected (but I am not very familiar with githb). There are only 15 images in the folder currently, and 10 are ones that I loaded. I am fine with deleting these and reloading them to the new repository location. It would then be a simple matter of fixing the image file paths in the actual How-To pages. As long as the documentation-wiki repository is  a good solution and won't interfere with the code, I'm happy to move everything over manually and fix broken image links in the wiki.

**Comment by dustymc** [comment]
Don't worry too much about the existing stuff; it's not really hurting anything anytime soon, just sort of mildly annoying when it changes (which throws merge warnings - and someone will probably eventually delete the "unused" folder). I can copy them across (eventually...) if that's easier. I'd mostly just like to update the procedures so that stuff ends up somewhere safer going forward.

It's sort of silly, but....

Issues allow drag-and-drop image uploading (to cloud.githubusercontent.com) - wiki does not for some mysterious reason. Open a wiki in one tab, open Issues/click new in another, drag-drop images to the Issue, copy the text after it loads, paste into wiki, save the wiki and close the issue tab without saving seems to work. I'm not sure if that's less-painful than the alternatives....

**Comment by campmlc** [comment]
Emily,
If you feel comfortable tackling the move, that would be a big help.
Because we also need to make the tutorials file available for people to
upload new images to. We are going to need constant access, and the problem
is much easier to resolve now with only a few images than it will be later.
Mariel

**Comment by ebraker** [comment]
Ok, the tutorial_image folder is now moved over to the documentation-wiki repository (https://github.com/ArctosDB/documentation-wiki/tree/master/tutorial_images) and the original folder deleted from the master code. All image links in the How To pages have been redirected and I updated the wiki documentation on how to upload images to reflect the new folder location.

**Comment by dustymc** [comment]
THANK YOU!!

**Comment by campmlc** [comment]
Thanks, Emily!
