### ISSUE TITLE
locality in use flag by any object (not just specimens)

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#850]
Currently locality detail page will say 'contains nothing and so should be deleted' if not attached to a specimen event. What about media?  Can we have localities flagged in use by any object including media.     
Use Case: MVZ images like landscapes and habitat which have been mapped without reference to a specimen

**Comment by dustymc** [comment]
Cannot replicate; re-open with example if this is valid.

<img width="455" alt="screen shot 2016-04-07 at 10 54 41 am" src="https://cloud.githubusercontent.com/assets/5720791/14361327/35891502-fcaf-11e5-8dff-a07638f51d33.png">
