### ISSUE TITLE
duplicate localities

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#865]
The new specimen-->event-->locality-->media-from-all-events display does not work "properly" (as a user might expect) when there are duplicate localities. That is, if Locality_ID=1 and Locality_ID=2 differ only by locality_id, specimens using events under Locality_ID=1 will NOT see Media related to events under Locality_ID=2. 

There exists a locality merger tool, but finding and merging localities with it is a haphazard process.

I propose we automate the merger tool, so that localities which differ only by locality_id are automatically detected and merged.

**Comment by campmlc** [comment]
I agree. There are too many identical localities that differ only by ID.

**Comment by mkoo** [comment]
AWG 2016-08-01: We like the paranoid version where all fields are identical before merging for automated clean-up

**Comment by dustymc** [comment]
Adding a blocker to this - the idea that our locality model is wrong keeps popping up (eg, #752) and we probably don't want to invest in writing code to a model that we're going to get rid of.

Are we going to change our locality model, or can I develop tools to it?

**Comment by DerekSikes** [comment]
I'm in favor of this-> "I propose we automate the merger tool, so that localities which differ only by locality_id are automatically detected and merged."

**Comment by dustymc** [comment]
Thanks, looks like consensus to me.

Do we need to discuss the future of the locality model before writing more code to it, or should I proceed with this?

@ccicero @mkoo

**Comment by DerekSikes** [comment]
I think it best to proceed. I don't want the somewhat lengthy discussion on the future of the locality model to slow down improvements to the current model that we can all benefit from now.

**Comment by jldunnum** [comment]
Agreed


______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by dustymc** [comment]
Bringing this to the top.

1) Scripts will constantly search for and merge duplicate (=differ by locality_id) localities behind the scenes.
2) The forms to manually merge almost-duplicate localities (and define "almost duplicate" however you want in the process) will remain as-is.

Please comment ASAP if there are reasons NOT to begin on this immediately.

@dperriguey

**Comment by dustymc** [comment]
This is now implemented in production
