### ISSUE TITLE
case-sensitivity in usernames

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#868]
Log in with WeIRd CaSE, things get weird - make login, myarctos, functionlib.inituser() case-insensitive

**Comment by jtgiermakowski** [comment]
Why should usernames be case insensitive? Or are you proposing the OPPOSITE?

**Comment by campmlc** [comment]
yes. That would be helpful.

Log in with WeIRd CaSE, things get weird - make login, myarctos,
functionlib.inituser() case-insensitive

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/ArctosDB/arctos/issues/868>

**Comment by campmlc** [comment]
I would prefer case insensitive. I logged in today via my cell phone and
had to go into change phone settings to stop autocapitalization before I
could successfully enter my username.
On Apr 14, 2016 5:10 PM, "Tom Giermakowski" <notifications@github.com>
wrote:

Why should usernames be case insensitive? Or are you proposing the
OPPOSITE?

**Comment by jtgiermakowski** [comment]
Oh, I see. Sorry, I come from Unix...

Wysłane z mojego Moto X

On Apr 14, 2016 20:17, Mariel Campbell <notifications@github.com> wrote:
I would prefer case insensitive. I logged in today via my cell phone and
had to go into change phone settings to stop autocapitalization before I
could successfully enter my username.
On Apr 14, 2016 5:10 PM, "Tom Giermakowski" <notifications@github.com>
wrote:

Why should usernames be case insensitive? Or are you proposing the
OPPOSITE?

**Comment by dustymc** [comment]
Every now and then I get a contact report from "user" in the vein of "OMG Arctos is totally broken!!", I go look, they're registered as "User." I thought that this might be less work than explaining case-sensitivity.

Mariel's comments have alarmed me, though. I can't really think of anything scarier than a device that doesn't output what a user inputs, and perhaps we shouldn't be encouraging carelessness in typing either.

(And Arctos is UNIX and UTF - a A and Á are all different characters, it takes extra work to pretend they aren't.)

**Comment by dustymc** [comment]
Reviving this, see https://github.com/ArctosDB/arctos/issues/4599 and https://github.com/ArctosDB/arctos/issues/4595

Login doesn't care about case, but some tools do. We can make login case-sensitive, or we can add a complexity (and computational cost, but I'm not sure that's significant - yet, anyway).

Help!

**Comment by ewommack** [comment]
> Login doesn't care about case, but some tools do. We can make login case-sensitive, or we can add a complexity (and computational cost, but I'm not sure that's significant - yet, anyway).

So this means that if you create your login with one set of cases, but enter your login with the wrong set, you are going to get error messages? e.g. Apple, but I log in with apple
or
We need to create logins only with lower case letters, because some tools cannot handle upper case? e.g. we should all have apple, and having a login in with Apple will not work for some tools

**Comment by dustymc** [comment]
Oh, I like parts of that.

Login could take whatever (so only one thing has to convert), everything gets ``lower()``ed for storage and use. So you could log in as ApplE, but as soon as that's done you're apple. I'd need to update data in whatever uses username, but only one time. Other than the case change, users shouldn't have to do anything.

These are active operators with uppercase characters in their usernames and github addresses - any objections/concerns?

 @susitna
 @Cynthia-Carr
 @Nicole-Ridgwell-NMMNHS
 @ErinKup
 @Mcilvainevc1
 @SilviaEPavan
 @Awkwardtree13
 @AdrienneRaniszewski

**Comment by campmlc** [comment]
To be clear, they could still use their cap login - so what would this affect that they might encounter via the UI?

**Comment by dustymc** [comment]
See also https://github.com/ArctosDB/arctos/issues/4616; I'd like to propose one more step:

* lower() all existing agent names of type 'login', constrain names of type 'login' to be lowercase

Moving to AWG agenda, this has been an increasingly frequent cause of avoidable problems lately.

**Comment by Jegelewicz** [comment]
Added to tomorrow's agenda

**Comment by dustymc** [comment]
AWG: go case-sensitive
