### ISSUE TITLE
Adding new parts to an existing record

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#872]
Request that a "Barcode" field be added to the Add Specimen Part tool under Edit from the Specimen Record, so that it is possible to add the barcode at the time of part creation. At the moment, this process requires two steps - one to create the part, and a second step to scan through all the existing parts to find the one that was just created and attach the barcode to it. Not only is this cumbersome, but it creates the risk of associating the barcode with the wrong part.

**Comment by dustymc** [comment]
added
