### ISSUE TITLE
reserved words in CSV headers

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#874]
1) upload CSV with column name "verbatim date"
2) get cryptic error message

We should sanitize CSV before sending it off to CF. This is a fairly rare (but very confusing) situation, please prioritize accordingly.

**Comment by mkoo** [comment]
develop an enhanced validation step for bulkloader?

**Comment by mkoo** [comment]
List of offensive/reserved words? Maybe we just need documentation and guidance in lieu of sanitizer for rare events.

**Comment by dustymc** [comment]
Closing - errors are easier to interpret in PG.
