### ISSUE TITLE
Log in page simplification

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#878]
I suggest that you remove the Login/Create New User box from the top right corner of the main login page (http://arctos.database.museum/login.cfm).  It is redundant on this page and can cause confusion to new users attempting to set up a user account.  I also suggest that the instructions on the page: "To create an account and log in, simply supply a username and password here and click Create Account."  be modified to include the requirements for username and password.  So perhaps "To create an account and log in, simply supply a username (only letters and numbers (ASCII characters A-Z, a-z, and 0-9), not starting with a number) and password (at least 8 characters long and include at least one letter, one number, and a special character such as "!"") here and click Create Account.

**Comment by dustymc** [comment]
> I also suggest that the instructions on the page: "To create an account and log in, simply supply a username and password here and click Create Account." be modified to include the requirements for username and password. 

The only password requirement for an account is that it's not NULL. The more complex password requirements are only for operators, and those requirements are spelled out when a user is authenticating to become an operator.

**Comment by Jegelewicz** [comment]
OK, but look at this from the standpoint of a curmudgeon curator, who doesn't like creating a password only to be told a day later (when they are invited to be an operator) that they need a new one because the one they selected doesn't meet the Arctos standards.  Many of my operators won't understand the reason for two levels of password complexity (and since I don't either, I can't explain it to them).

**Comment by campmlc** [comment]
I agree that the process of creating a new user/operator account is very
confusing and time consuming, even for someone who had done it many times,
and having to create two separate passwords during the process adds to the
difficulty. Could we put a statement on the login page to the effect that
there are two categories of passwords, and you should choose on or the
other depending on whether you will be a user only vs an operator? And give
the requirements for the operator password up front? That would save a step.

**Comment by dustymc** [comment]
> the reason for two levels of password complexity

User accounts do not authenticate with Oracle. If the account gets compromised, oh well - the "hacker" could have gained the same access by simply creating an account.

Operator accounts do authenticate with Oracle. If the account gets compromised an attacker can do anything the compromised operator could do, so additional security measures are required. (But I don't think there are a lot of FSB agents trying to hack Arctos to change all your hind foot length data....)

I of course welcome usability suggestions and have no real attachment to the current forms or procedures, but whatever we do needs to accommodate all users (eg, people who just want to customize forms or download data, people with smaller screens, etc.) and not just curmudgeoney curators. (Or at least that's my outlook - the AC/WG can redefine our target audience if they want to.)

**Comment by campmlc** [comment]
I agree with the two levels of passwords. But we should make the
instructions clearer, and separated by 1) if you just wish download data,
you only need  a "not NULL" password", but if you 2) are trying to set up
an operator account, please use the following criteria for password
creation etc. This will solve the issues for curmudgeoney curators and even
make life easier for the rest of us :)

**Comment by dustymc** [comment]
Could you make a photoshop/crayon/whatever mockup of what you're visualizing?

**Comment by dustymc** [comment]
Comments from merged issues #879, #877

- yes, we can make the submit-with-defaults work better (I think some library it uses changed)
- most accounts seem to be created from the header - adding stuff to the login page won't be seen by those users
- there are no/extremely limited username/password restrictions on most users. Operators should be reading documentation - if they can't do that, do we really want to then set them free in locality-land?!?
- Most users are not operators, they just want to customize a form etc.

**Comment by dustymc** [comment]
>yes, we can make the submit-with-defaults work better (I think some library it uses changed)

Updated, try it out at http://arctos-test.tacc.utexas.edu/login.cfm

**Comment by Jegelewicz** [comment]
Here's an example.
![log in example](https://cloud.githubusercontent.com/assets/5725767/15233580/34c1bcf4-1867-11e6-8d60-56864c80a203.jpg)

**Comment by dustymc** [comment]
Added "operator documentation" link from /login

**Comment by dustymc** [comment]
closing - please reopen and comment if anything remains unaddressed
