### ISSUE TITLE
Accession Creation Form

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#880]
After creating a new Accession, the user is taken to the form for editing an Accession and offered the following options at the bottom of the form:
1. Save Changes
2. Quit without saving
3. Delete
4. Specimen List
5. Berkeley Mapper

Of course, I select "Save Changes" and what happens?  Nothing!  I am sitting at the same screen wondering if anything has been saved and how to exit.  Can we have an option to "Save Changes AND Exit"?  Otherwise I am selecting "Save Changes", then "Quit without saving", just to be sure that I don't lose my record.  ("Quit without saving" sounds to me like whatever I entered will not be retained.)

**Comment by dustymc** [comment]
>I select "Save Changes" and what happens? Nothing! 

If your browser doesn't reload, something is very wrong/non-standard with your machine.

I suppose we could add a "things have saved, click here to go back where you came from" confirmation page after every save, but that would require a LOT of extra clicks and significant development.

"Quit without saving" is now (in test) labeled "Discard unsaved changes." It exists to ensure (as much as anything can be ensured in a browser) that you're seeing what's in the database and not seeing unsaved changes. For example, if you edit a text field and click reload, in most browsers your unsaved text will remain in the field - if you leave the page, you'll lose the change. This button leaves and returns which should force your browser to refresh. (Shift-reload does roughly the same thing.)

**Comment by Jegelewicz** [comment]
When I say nothing, I mean that to a casual user it isn't apparent that anything has happened.  I think that it might be clearer if there were the following options:

Save and continue - saves your changes and keeps you in the form
Save and quit - saves your changes and takes you to a blank form for entering a new accession
Discard unsaved changes - discards the changes and keeps you in the form
Discard unsaved changes and quit - discards your changes and takes you to a blank form for entering a new accession

**Comment by campmlc** [comment]
When I click either "Save Changes" or "Discard unsaved changed" in Chrome
or Firefox, my browser reloads, and the new information is incorporated or
removed. Both "Save Changes" and "Discard unsaved changes" keep you in the
form.  To quit, you have to use the browser back arrow, which is the case
for most Arctos windows. We don't seem to have "quit" as an option anywhere
currently.

**Comment by dustymc** [comment]
>We don't seem to have "quit" as an option anywhere currently.

A "quit" button that zapped you off somewhere would be very frustrating. 

Specific example: From new accn, 4% of users edit an accn, 3% go to agents, ~1% go to manage users, check bulkloader status, and data entry, and the other ~90% do something that's not statistically interesting to Analytics. At best, 96% of users wouldn't like wherever we might send them.

That pattern is generally true everywhere else, and it's why the site navigation lives in the header - wherever you want to go next is (about - the header could always be improved) one click from wherever you are. There is no single pathway through Arctos, there's very seldom one way of approaching or doing most any thing, and I don't think there's any trend whatsoever in how users get from one node to the next.

**Comment by amgunderson** [comment]
Please do not make more buttons. If you want to quit without saving, don't
click save. If you want to save you click save. I would advocate to remove
the quit without saving button that I see there now, it takes you to the
find accession page which I can get to from the header. If we keep the quit
without saving button it should just reload the page without saving (which
you can already do by hitting reload).
Aren

On Wed, May 18, 2016 at 3:13 PM, dustymc <notifications@github.com> wrote:

> We don't seem to have "quit" as an option anywhere currently.
>
> A "quit" button that zapped you off somewhere would be very frustrating.
>
> Specific example: From new accn, 4% of users edit an accn, 3% go to
> agents, ~1% go to manage users, check bulkloader status, and data entry,
> and the other ~90% do something that's not statistically interesting to
> Analytics. At best, 96% of users wouldn't like wherever we might send them.
>
> That pattern is generally true everywhere else, and it's why the site
> navigation lives in the header - wherever you want to go next is (about -
> the header could always be improved) one click from wherever you are. There
> is no single pathway through Arctos, there's very seldom one way of
> approaching or doing most any thing, and I don't think there's any trend
> whatsoever in how users get from one node to the next.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ArctosDB/arctos/issues/880#issuecomment-220185422>
>



-- 
Aren Gunderson
Mammals Collection Manager
University of Alaska Museum of the North <http://www.uaf.edu/museum>
907 Yukon Drive
Fairbanks, AK 99775
amgunderson@alaska.edu
907-474-6947
