### ISSUE TITLE
Loan Institutions and addresses

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#881]
I'm wondering if it is possible to pull up a list of loans from a given year and include the institutions or shipping addresses of the agents to which the loans were sent. This would be very useful for tracking usage by state or country; also even more useful in that we could use the list to contact all the agents who borrowed material in a given year to check on publication or loan status etc. I'm trying to figure out a better way to track who has published papers on what specimens in a given year, which seems an extraordinarily difficult thing to do.

**Comment by dustymc** [comment]
>list of loans from a given year and include the institutions or shipping addresses 

Report/WriteSQL then

```
select
  loan_number,
  loan_status,
  address
from
  trans,
  collection,
  loan,
  shipment,
  address
where
  trans.transaction_id=loan.transaction_id and
  trans.collection_id=collection.collection_id and
  loan.transaction_id=shipment.transaction_id and
  shipment.SHIPPED_TO_ADDR_ID=address.address_id and
  trans_date like '2015%' and
  collection.guid_prefix='MSB:Mamm'
```

>who has published papers on what specimens in a given year

```
select
  short_citation,
  guid_prefix,
  count(*) n
from
  publication,
  citation,
  cataloged_item,
  collection
where
  publication.publication_id=citation.publication_id and
  citation.collection_object_id=cataloged_item.collection_object_id and
  cataloged_item.collection_id=collection.collection_id and
  guid_prefix='MSB:Para' and
  publication.published_year='2015'
group by
  short_citation,
  guid_prefix
order by
  short_citation
```

If you find something useful in that we can build a report (and there are lots of loan/citation reports under the reports tab)
