### ISSUE TITLE
Object+Barcode to Container

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#883]
We are starting a large project to add barcodes to existing tissue vials. At least initially the upload of barcodes to specimen records with be done using the Object+Barcode to Container tool in Object Tracking. However, there a some issues that I would like to see revised for ease of use and error control.

1) "Parent Cont Type" should be changed to read "Move to Container Type" or "Barcode Container Type". My student was adding in cryovial barcodes and misunderstood this. She assumed the "parent" of a cryovial was a freezer box - this resulted in all the cryovials being converted to freezer boxes inside the freezer box positions. 

2) The "Move to Container Type" field above should have a null default value so as not to change the type of an existing container unless the user specifically intends to do so (it certainly shouldn't be set on "Nalgene" as the automatic default requiring manual change to a different value.)

3) Please if at all possible add a live link to the specimen record from this page, so that the specimen record can be accessed easily for verification.

**Comment by campmlc** [comment]
![screenshot 2016-05-19 18 12 12](https://cloud.githubusercontent.com/assets/14808196/15413472/c0924ef2-1ded-11e6-8072-7f9ad51f56f7.png)

**Comment by dustymc** [comment]
>"Parent Cont Type" should be changed to read "Move to Container Type" or "Barcode Container Type". 

I pretty strongly disagree. We're (fairly) consistent (I hope) with the parent-child terminology and I'm not anxious to change that - it's common vocabulary regarding hierarchical data models. I'm absolutely not going to introduce new terminology to one of dozens of forms. I'm always up for making things more clear, I just don't think getting rid of parent-child is a pathway to clarity.

Containers are globally shared. Your student should REALLY not be in there if they can't be bothered to read the documentation. They are eventually going to do something that significantly affects other collections, and probably not in a happy sort of way. https://github.com/ArctosDB/arctos/issues/745

>The "Move to Container Type" field above should have a null default

Done

>live link to the specimen record

Done

And FYI I tend to filter-ignore things which have been assigned - someone else has claimed/is going to fix it, it doesn't need my attention. You can @campmlc @KyndallH to get a user's attention.

**Comment by campmlc** [comment]
I think the confusion arises when the same form is used to assign a new
barcode to an existing container vs moving a container to a new parent.
People including myself using the form for the former task find the
terminology confusing. It would be good to use terminology that can apply
to both cases, to minimize confusion.  Perhaps we can add a link to the
documentation above Parent Container Type to explain this?

**Comment by dustymc** [comment]
>used to assign a new barcode to an existing container

This should never happen - please explain.

**Comment by campmlc** [comment]
We are barcoding legacy cryovials in the DGR Locator and moving them into
Arctos object tracking. These are existing vials that are being given
barcodes for the first time. The barcodes are in Arctos as cryovial labels.
They are applied to legacy cryovials, scanned into position in freezer
boxes in Arctos object tracking, and then the barcode must be associated
with the appropriate part in the specimen record using Object + barcode to
container. This is the protocol in use at UAM, as I understand it.

**Comment by dustymc** [comment]
Thanks - that helps.

I don't really see any "database difference" between that and sticking a barcode to a new container, and I don't see anything scary (like trying to update the barcode of an existing container record!) about what it seems you're doing.

It's somewhat behind the scenes, but putting a part into a tube is just moving a container, or establishing a child-->parent relationship. (All parts simultaneously exist as containers.) It's different in that one of the containers (the part) has some restrictions (can't have barcode, can't act as parent), but other types of containers have specific rules as well.

We "create containers" by uploading series of %label% container_types, then we "create" containers that can actually do something useful by switching those to not-label container_type, presumably in conjunction with/anticipation of some sort of physical action (like sticking them to things we want to find later). The former just adds predictability - you can't create containers by scanning your Doritos or typING We1rd th!nGs into a barcode field or etc. - the latter enables functionality beyond mere existence to the barcode. Is that the point of confusion?

I believe UAM:Mamm makes the part-->barcode link as part of data entry, starting with sticking half a barcode on the "field notes." Note that it's an asynchronous process - maybe data entry happens first (in which case you know MSB:Mamm:1234's liver is in SOMEBARCODE but have no idea where the tube is), or maybe "container installation" happens first (in which case you can find SOMEBARCODE but have no idea what's in it), and there can be years between those events. Whenever both happen, you can find the part. Maybe that's somehow useful in establishing your workflows.

**Comment by campmlc** [comment]
Yes, we do make the part-to-barcode link in data entry for all incoming
material, using two part barcodes with one label placed on the data sheets,
the other on the part. But we will need to use Object+BC ->Container to add
barcodes to existing parts in existing containers for all our legacy
material.

**Comment by amgunderson** [comment]
I agree with Dusty, don't change "parent container type" - that is exactly
what goes in that field, just explain parents and children to your
students. We barcoded 60,000 cryovials with this page and it worked great.
Change the default container type to cryovial, that would be nice.
Hyperlink to the specimen record, sure.
Aren


On Fri, May 20, 2016 at 9:10 AM, Mariel Campbell <notifications@github.com>
wrote:

> Yes, we do make the part-to-barcode link in data entry for all incoming
> material, using two part barcodes with one label placed on the data sheets,
> the other on the part. But we will need to use Object+BC ->Container to add
> barcodes to existing parts in existing containers for all our legacy
> material.
>
>
> On Fri, May 20, 2016 at 10:25 AM, dustymc <notifications@github.com>
> wrote:
>
> > Thanks - that helps.
> >
> > I don't really see any "database difference" between that and sticking a
> > barcode to a new container, and I don't see anything scary (like trying
> to
> > update the barcode of an existing container record!) about what it seems
> > you're doing.
> >
> > It's somewhat behind the scenes, but putting a part into a tube is just
> > moving a container, or establishing a child-->parent relationship. (All
> > parts simultaneously exist as containers.) It's different in that one of
> > the containers (the part) has some restrictions (can't have barcode,
> can't
> > act as parent), but other types of containers have specific rules as
> well.
> >
> > We "create containers" by uploading series of %label% container_types,
> > then we "create" containers that can actually do something useful by
> > switching those to not-label container_type, presumably in conjunction
> > with/anticipation of some sort of physical action (like sticking them to
> > things we want to find later). The former just adds predictability - you
> > can't create containers by scanning your Doritos or typING We1rd th!nGs
> > into a barcode field or etc. - the latter enables functionality beyond
> mere
> > existence to the barcode. Is that the point of confusion?
> >
> > I believe UAM:Mamm makes the part-->barcode link as part of data entry,
> > starting with sticking half a barcode on the "field notes." Note that
> it's
> > an asynchronous process - maybe data entry happens first (in which case
> you
> > know MSB:Mamm:1234's liver is in SOMEBARCODE but have no idea where the
> > tube is), or maybe "container installation" happens first (in which case
> > you can find SOMEBARCODE but have no idea what's in it), and there can be
> > years between those events. Whenever both happen, you can find the part.
> > Maybe that's somehow useful in establishing your workflows.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ArctosDB/arctos/issues/883#issuecomment-220652858>
>
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ArctosDB/arctos/issues/883#issuecomment-220663826>
>



-- 
Aren Gunderson
Mammals Collection Manager
University of Alaska Museum of the North <http://www.uaf.edu/museum>
907 Yukon Drive
Fairbanks, AK 99775
amgunderson@alaska.edu
907-474-6947
