### ISSUE TITLE
Project loan and accession csv download

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#885]
Add tool to be able to download loans and accessions as csv from the project page.

**Comment by dustymc** [comment]
I need to know exactly what data you want to consider this.

**Comment by campmlc** [comment]
all loans and/ or accessions associated with a particular project, from the
info displayed in the project edit page. Should download in same format as
csv download from search loans or accessions page.

**Comment by dustymc** [comment]
So ONLY the transaction stuff, NOT anything from specimens-and-beyond - right?

**Comment by campmlc** [comment]
We can get to the specimens from the regular public (non-edit) project
page. From the edit page, we see accessions, loans, publications - it would
be good to be able to download all these.

**Comment by campmlc** [comment]
While you are mucking about with this in projects, you added funding (US
dollars) recently, but it would be great to add "funding source" with the
ability to put in a grant ID, e.g. NSF grant number. I can add this to a
separate issue if that is preferable.

**Comment by dustymc** [comment]
>funding source

<img width="447" alt="screen shot 2016-06-01 at 8 50 41 pm" src="https://cloud.githubusercontent.com/assets/5720791/15733412/90c0677a-283a-11e6-9a1d-d4b8b363089b.png">

**Comment by campmlc** [comment]
That works - is it in test?
Searchable fields?

**Comment by dustymc** [comment]
It's in prod. Agents and roles are searchable.

**Comment by dustymc** [comment]
added csv option to edit project
