### ISSUE TITLE
download csv from loan search

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#886]
Seems to be broken? I search on "%Canis lupus baileyi%" in Nature of Material, get a results list, click on dowload csv, and a bunch of unrelated loans pop up and no csv download occurs.

**Comment by dustymc** [comment]
You don't need the % there (or in any other search form, unless it explicitly says default match is entire something-or-another), and it's breaking the form. I'll update.

**Comment by dustymc** [comment]
fixed v7.4++
