### ISSUE TITLE
Agent merge and loan search

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#889]
Dusty, 
I need to merge two agents with entries from MSB and MVZ, and before I do so I want to confirm that all the agent activity from the bad duplicate will indeed be transferred over to the valid agent. Is this so? The bad duplicate (lacks accent mark) has most of the agent activity.
Guillermo D'Elía = valid
Guillermo D'Elia = bad duplicate

Also, I am having trouble searching on transactions for this agent. When I enter either name in loan search for agent/role, I get the following error:

	An error occurred while processing this page! 
Error Executing Database Query. 
[Macromedia][Oracle JDBC Driver][Oracle]ORA-00933: SQL command not properly ended

**Comment by dustymc** [comment]
Agent ACTIVITY is transferred. Agent NAMES are not; please make sure the good one conforms to https://arctosdb.org/documentation/agent/#create (esp. "Include common ASCII-128 (A-Z, no accents or foreign characters) variants. “Николай Е. Докучаев” is an acceptable Preferred Name, but include as a nonpreferred name “Nikolai Dokuchaev.” Agent “Raúl Gutiérrez” should include the nonpreferred name “Raul Gutierrez.”")

>An error occurred while processing this page!

Woops! It'll be fixed for next release - in the meantime you can double up the apostrophe to get around the problem. http://arctos.database.museum/Loan.cfm?Action=listLoans&agent_1=d%27%27elia
