### ISSUE TITLE
make an agent add button in the pub creation screen

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#892]
In the event that a publication author is not yet in Arctos, provide an add agent link from the publication entry screen.

**Comment by dustymc** [comment]
The ability to create agents (given proper rights) could/would exist in all agent picks, not just publications.

#732 is a blocker - this code is not something I'd want to write or maintain in two places.

**Comment by mkoo** [comment]
Consensus from AWG 2016-08-01 See #732

**Comment by mkoo** [comment]
Closing
