### ISSUE TITLE
Duplicate agent cleanup request for Mclean

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#895]
MVZ has incorrect agent Bryan Mclean down as the agent for two loans below instead of the correct: Bryan S. Mclean. These agents are "not the same as" each other.
outside contact for Loan MVZ:Mamm 2014.8057.Mamm
outside contact for Loan MVZ:Mamm 2015.8122.Mamm
Also, MSB has the same incorrect Bryan down for 
105 attributes for 58 MSB:Mamm specimens
It should be Bryan S. Mclean for all the above. I can't fix either of these using the standard tools with my access.

Finally, Bryan Mclean is listed as associated with Mammalogy 2013 and Mammalogy 2014 projects, but when I search on these I get a 404 error.

I'd like to clean these up to avoid future mishaps of assigning the incorrect name.

**Comment by dustymc** [comment]
>MVZ has incorrect agent Bryan Mclean down as the agent for two loans below instead of the correct: Bryan S. Mclean. These agents are "not the same as" each other.
outside contact for Loan MVZ:Mamm 2014.8057.Mamm
outside contact for Loan MVZ:Mamm 2015.8122.Mamm

@ccicero can you coordinate checking/fixing these?

>105 attributes for 58 MSB:Mamm specimens

I changed these.

Please comment on #903.

>Finally, Bryan Mclean is listed as associated with Mammalogy 2013 and Mammalogy 2014 projects, but when I search on these I get a 404 error.

See #904.

**Comment by dustymc** [comment]
Is this all happy? Tentatively closing....
