### ISSUE TITLE
Arctos Media uploader - expiration date

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#897]
There are ~2,000 files which have been loaded to Arctos >60 days ago and which have not been used in Media records. We have limited disk space on the Arctos web server (the only load target currently available to the CF interfaces). I'll send an email asking the uploading users how to proceed with these, but we need a better plan going forward. 

There is no way for a user to delete files which they've uploaded, and I'm extremely resistant to making delete on that server available to anyone in any capacity. I suspect that's where most of these originate. Can we just automatically delete things that haven't been used after some amount of time (if so, how much)? If not, how can we prevent this pileup? 

Storing files which will eventually be used isn't really much of a problem, I just can't tell what is being/will be processed from what's trash.

Uploaded files which have been used in Media are not part of this problem - those are eventually transferred to TACC's fileservers (which have essentially unlimited space) and Media are updated accordingly (one reason we recommend accessing the media via eg http://arctos.database.museum/media/10248258?open rather than http://web.corral.tacc.utexas.edu/UAF/es/2012_01_11/jpegs/ES33518_1.jpg - the former will always follow the file, the latter may stop working at any time). 

https://github.com/ArctosDB/documentation-wiki/wiki/How-to-Upload-Media-to-TACC and https://github.com/ArctosDB/documentation-wiki/wiki/How-to-Create-Media-(Images) seem to adequately address the options (eg, it's possible to SCP things that take a lot of disk directly to TACC's fileservers).

**Comment by AJLinn** [comment]
Auto-deleting after ~60/90 days seems like a good option to me.

I'm trying to understand better the preferred process for loading images to TACC first instead of pulling from local computer hard drive, which I think is what you're referring to here:

>  (one reason we recommend accessing the media via eg http://arctos.database.museum/media/10248258?open rather than http://web.corral.tacc.utexas.edu/UAF/es/2012_01_11/jpegs/ES33518_1.jpg - the former will always follow the file, the latter may stop working at any time). 

Our typical workflow is to add media as we're working in a specimen record and we discover we need to add the image. By uploading to TACC first, if I read the [How To](https://github.com/ArctosDB/documentation-wiki/wiki/How-to-Upload-Media-to-TACC) properly, I wouldn't be able to link them immediately, which is a problem with my workflow. Am I mis-understanding? Maybe we could host a Media Upload webcast or something for others who might be having the same problems? Eventually we hope to have anywhere from 2-10 media files associated with every specimen record in the UAM:EH collection so I'd like to be sure we're doing this properly before we get out of hand.

**Comment by dustymc** [comment]
>Auto-deleting after ~60/90 days seems like a good option to me.

Thanks!

I don't really have a preferred process - if SOMEONE loads directly to the webserver, and they will, the scripts have to exist and it doesn't really matter how many files they have to move. (Famous last words?)

@ccicero can expand on the SCP process, but I believe that they're not immediately available on the web and require some processing by TACC before you'll get back (fairly-stable) URLs, which you could then bulkload as Media records. 

The only "disadvantage" of the direct-load process I can imagine from your end is that the URL *will* change. Once a Media record exists in Arctos, and it does immediately when you use the web loader, internal processes use media_id and the ?open redirect service becomes available for external use, so you should no longer have any need of the direct URL anyway.

If for whatever reasons your workflow involves dealing with individual specimens/images/whatever, I see no problems with what you seem to be doing. If it's somehow easier to eg, create a big batch of images with something pointing to exactly one specimen predictably embedded in the filenames, I might be able to use that in conjunction with the SCP loader to save some clicking.

**Comment by amgunderson** [comment]
auto delete after 90 days is a good idea.

**Comment by dustymc** [comment]
also need to drop the "you should delete...." message on the forms

**Comment by amgunderson** [comment]
I agree with Angie, auto delete, but 30 days should suffice.

**Comment by sharpphyl** [comment]
So does this mean that when I get the message below, I can ignore it?  If this told me that my media will be deleted in 30 or 60 days if I don't use it, I would be fine and I wouldn't have gone (more than usual) nuts searching through the handbook trying to figure out how to delete it.  Or are you talking about something else?

![screen shot 2017-08-11 at 2 40 57 pm](https://user-images.githubusercontent.com/15368365/29231126-3bfe2612-7ea3-11e7-8e0d-6b0640e379b7.png)

**Comment by dustymc** [comment]
@sharpphyl  that's correct, there's no need to track down "orphans."

**Comment by dustymc** [comment]
This is implemented in Admin/cleanImages as part of the push to TACC process. Currently working with TACC towards a process which would entirely eliminate Media on the webserver (https://github.com/ArctosDB/arctos/issues/1446); if that works this will be irrelevant, if it doesn't this may need revived and implemented as a scheduled task.
