### ISSUE TITLE
agent relationships

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#906]
Change all agent relationships to "is {relationship} of"
Add a trigger on the CT to make sure they stay that way
Update displays to read as a triplet:

{thisAgent} {relationship} {relatedAgent}

@ccicero

**Comment by dustymc** [comment]
Not sure what we were trying to do here, sending back for discussion....

**Comment by Jegelewicz** [comment]
I think this is the way it currently works?

![image](https://user-images.githubusercontent.com/5725767/95887001-8d044c00-0d3c-11eb-8efe-124bea706415.png)

But why do the relationships appear in two different ways? Seems like they should look the same whether they are "to" or "from"?

Also, we need to fix this.

![image](https://user-images.githubusercontent.com/5725767/95887511-292e5300-0d3d-11eb-999d-d68e64eab6af.png)

**Comment by Jegelewicz** [comment]
Closing for lack of interest - fixed end date thingee.
