### ISSUE TITLE
taxonomy - "invalid" names

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#912]
From @DerekSikes

> ...will be entering specimen taxon IDs as they are on the label. A bunch of the names entered will be invalid names (junior synonyms or homonyms etc).
> 
> It would be great if the specimen search form in the Identification section had a way for us to search on the validity of a name.
> 
> A envision a drop down menu that lists options from the 'relationship' menu in the non-classification form of the taxonomy table.
> 
> Eg 'junior synonym of' or 'nomen dubium' etc.
> 
> This way we can periodically search for any specimens that have their current ID as a name that is not valid and fix them by updating their IDs to the valid name.
> 
> And I'll repeat my plea for the addition of a simple field like the 'taxonomic status' field in ITIS:
> 
> http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=149798
> 
> which has values of 'valid' or 'invalid'
> 
> This would make it much easier to search to find all identifications that use invalid names (since there are many ways to be an invalid name).

We currently have two types of taxon relationships (examples from http://arctos.database.museum/name/Echidna)
1. The  'relationship' menu in the non-classification form of the taxonomy table relates taxon names to taxon names, eg
   `Tachyglossus → junior homonym → Echidna ( Authority: ITIS)`
2. The classifications from GlobalNames have "embedded relationships", eg

```
canonical name: Echidna
name string: Echidna Link, 1806

Classification:
Animalia (kingdom)
Chordata (phylum)
Reptilia (class)
Squamata (order)
Viperidae (family)
Bitis (genus)
```

I believe this request involves CLASSIFICATIONS, not NAMES; _Echidna_ is a "valid" name when used for an eel, and an invalid (according to some users for some purposes, anyway) name when used for a moth. The relationships between taxon names can only work as intended some of the time; they're context-dependent.

The data from GlobalNames do not include a reason for including "Bitis" or "Actias" under Echidna, and so can't be used to get at things like "junior synonym of"; we can just get that some source thinks that someone at some time used "Bitis" for some critters that someone at some time labeled "Echidna" with no indication of WHY.

"Valid" can only apply to classifications (and only "according to someone in some context"), not names. _Echidna_ is valid if you're working with eels or viruses, invalid if you're working with vipers or weird spiky mammals. Invalid NAMES - things not supported by a "taxonomy publication" (whatever THAT means) should not exist in Arctos.

I believe the "correct" approach is probably to move our taxon relationship data into classifications, similar to the data we get from GlobalNames, and abandon our name<--->name relationship model. Our current relationships are  somewhat nonsensical - Echidna-the-virus has nothing (that I know of!) to do with Tachyglossus, and that is not at all clear from our data. Doing so may take some model or form changes.
1. We'd probably want to keep our "authority" data, even though much of it's sorta shady. The best taxon authority would of course be publications, and I'm not sure how we'd fit that level of structure into classifications, which are necessarily only loosely-structured.
2. The migration path is likely to be somewhat murky. Is TaxonA  "some relationship of" TaxonB (in the "Arctos Plants" classification) or TaxonB (in the "Arctos" classification)?
3. It's not entirely clear how such a transformation might interact with other taxonomy issues, see eg https://github.com/ArctosDB/arctos/issues/735

SO, we certainly can do whatever with the data we now have in Arctos, but perhaps it's worthwhile to back up and examine what we have and what we're trying to do before investing in what may be a dead-end model.

**Comment by DerekSikes** [comment]
"I believe the "correct" approach is probably to move our taxon relationship data into classifications, "

Agreed!

**Comment by Jegelewicz** [comment]
Closing to consolidate issues See #1700
