### ISSUE TITLE
Any Geographic Element Search

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#914]
Can we add Locality Nickname and/or Locality Remarks to the fields searched by Any Geographic Element on the specimen search page? This would allow searches on shorthand locality names/nicknames used by cms and researchers that may not be in the specific locality.

**Comment by dustymc** [comment]
>Locality Nickname

Seems reasonable to me.

>Locality Remarks

Seems less reasonable - I think that would return a lot of "...has nothing to do with {your search terms}..." data.

Quick discussion at next AWG meeting?

**Comment by dustymc** [comment]
Added locality name, rewrote SQL, checked and rebuilt indexes to improve performance.
