### ISSUE TITLE
Project/Publication additions

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#916]
In order to create a new project or publication you have to use the "Search - Publications/Projects" option from the main menu.  Could we also have options under "Manage Data" for "Publications/Projects" then "Find Publications/Projects" or "Create Publications/Projects" to be consistent with other parts of Arctos?

**Comment by dustymc** [comment]
Those options were purposefully removed in an attempt to reduce duplicates. There are lots of ways to "spell" projects and, perhaps somewhat to a lesser extent, publications, and many projects and publications are shared across collections (so can "magically appear" from any user's perspective). Spelling variations are often not detected by the DB, which leads to denormalization and erroneous data (eg, funky usage statistics). The idea was that forcing users to go through the search page might lead to detecting variations before creating (almost)duplicates.

I briefly scrolled around through publications which share short_citation and found a few duplicates.

````
Virginia R. Rausch and Robert L. Rausch. 1993. Karyotipic characteristics of <i>Sorex tundrensis</i> Merriam (Mammalia:
Soricidae), a Nearctic species of the <i>S. araneus</i> group. Proceedings of the Biological Society of Washington 106(2
):410-416.

Virginia R. Rausch and Robert L. Rausch. 1993. Karyotypic characteristics of <i>Sorex tundrensis</i> Merriam (Mammalia:
Soricidae), a nearctic species of the <i>S. araneus</i>-group. Proceedings of the Biological Society of Washington 106:4
10-416.


Robert T. Moore. 1939. Two new races of <i>Carpodacus mexicanus</i>. Proceedings of the Biological Society of Washington
 52:105-112.

Robert T. Moore. 1939. Two new races of Carpodacus mexicanus. Proceedings of the Biological Society of Washington 52:105
-112.

R. Eduardo Palma and Angel E. Spotorno. 1999. Molecular Systematics of Marsupials Based on the rRNA 12S Mitochondrial Ge
ne: The Phylogeny of Didelphimorphia and of the Living Fossil Microbiotheriid <i>Dromiciops gliroides Thomas</i>. Molecu
lar Evolution and Ecology 13(3):525-535.

R. Eduardo Palma and Angel E. Spotorno. 1999. Molecular Systematics of Marsupials Based on the rRNA 12S Mitochondrial Ge
ne: The Phylogeny of Didelphimorphia and of the Living Fossil Microbiotheriid <i>Dromiciops gliroides</i> Thomas. Molecu
lar Evolution and Ecology 13(3):525-535.

R Devkota, S V Brant, A Thapa, E S Loker. 2012. Sharing schistosomes: the elephant schistosome Bivitellobilharzia nairi
also infects the greater one-horned rhinoceros (Rhinoceros unicornis) in Chitwan National Park, Nepal. Journal of Helmin
thology: 88(01):32-40

R. Devkota, S.V. Brant, A. Thapa, E.S. Loker. 2012. Sharing schistosomes: the elephant schistosome Bivitellobilharzia na
iri also infects the greater one-horned rhinoceros (Rhinoceros unicornis) in Chitwan National Park, Nepal. Journal of He
lminthology 88(01):32-40.

Eric S Loker and Sara V Brant. 2006. Diversification, dioecy and dimorphism in schistosomes. Trends in parasitology 22(1
1):521-8.

Eric S. Loker and Sara V. Brant. 2006. Diversification, dioecy and dimorphism in schistosomes. Trends in Parasitology 22
(11):521-528.
````
I'm not sure if that's evidence that we still have a problem, or that the pathway to creating projects/pubs is useful (it used to be a LOT easier to find problems!), or ???? 

Implementing DOIs has also certainly helped reduce dups in publications, which may be more reason to allow more straightforward pathways to creation.

Adding "needs discussion" - I don't really see compelling evidence of anything in the data, so I'm happy to do whatever with the forms.
