### ISSUE TITLE
Neotominae (subfamily)

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#920]
I have specimens that are identified to the subfamily Neotominae.  When I try to upload them through the bulkloader I get an error saying Neotominae is not a valid Taxon Name.  According to the documentation, it seems to me that Neotominae should work.  Suggestions anyone?

**Comment by campmlc** [comment]
Did you check to make sure the spelling is exact, and that you don't have
any leading or trailing spaces? I was able to find it in Taxonomy Search.

**Comment by Jegelewicz** [comment]
I checked all that.  When I try to enter it directly through the data entry screen I get this:
![neotominae](https://cloud.githubusercontent.com/assets/5725767/17406614/67121324-5a21-11e6-8e9c-b3549a8136bb.JPG)

**Comment by campmlc** [comment]
Search on Taxon Term. It is a subfamily, not a scientific name.

**Comment by Jegelewicz** [comment]
Yes.  My specimens are identified down to this subfamily.  What I am trying to decide is how do I get that into Arctos?

**Comment by campmlc** [comment]
You should be able to load that as the name in Arctos, since the term
exists in Arctos classification. Try entering the name in the single record
data entry screen as a test.

**Comment by Jegelewicz** [comment]
I tried that and got the message above when I tabbed out of the field.

**Comment by Jegelewicz** [comment]
When I attempt to bulkload these records, the bulkloader marks them as TAXON not found.

**Comment by campmlc** [comment]
Try it now.

**Comment by Jegelewicz** [comment]
Woohoo!  It worked!
