### ISSUE TITLE
ES Attributes

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#923]
Can we have the following attribute added to ES collections please?
unformatted measurements
and the following part?
podials

Thank you!

**Comment by ccicero** [comment]
unformatted measurements added to ES code table 8/18/2016.

**Comment by Jegelewicz** [comment]
I'm not sure why, but when I'm attempting to bulkload some records in an ES collection with the unformatted measurements attribute it is telling me that it is invalid.

**Comment by Jegelewicz** [comment]
This is still not working.  When I'm attempting to bulkload some records in an ES collection with the unformatted measurements attribute it is telling me that it is invalid.

**Comment by campmlc** [comment]
Teresa, can you send a copy of the measurement values or the data file, and
a screenshot of the error message?

**Comment by Jegelewicz** [comment]
![capture](https://cloud.githubusercontent.com/assets/5725767/18146971/d714a172-6f8f-11e6-989f-d992d19f90ee.JPG)

**Comment by Jegelewicz** [comment]
I left this record in the bulkloader if that helps.

**Comment by campmlc** [comment]
Not sure how to solve this one. Someone else want to take a look? The attribute appears to be spelled correctly. Teresa, can you check that there isn't a leading or trailing space? Is this the only attribute showing an error, or are you getting a list? If a list, you may need to check the validity of your accession. 
Teresa, can you attach a csv of the record you are loading?

**Comment by Jegelewicz** [comment]
Oh!  I think I figured it out!  I had "mm" in the attribute units column, but unformatted measurements apparently doesn't allow the use of that field.  Once I deleted that it worked for the record I had in the bulkloader.  I'll attempt some more today to see if it works for the rest of my records.

**Comment by Jegelewicz** [comment]
Yep, that was it.
