### ISSUE TITLE
ES Parts

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#925]
Can we add "unicuspid tooth" to the ES collection parts please?

**Comment by campmlc** [comment]
Just making sure that the breakdown of various tooth types is necessary for
ES. Unicuspid is a version of premolar, which already exists in the table.
Also, ES has both "canine tooth" and "fang tooth" as values. Can these be
consolidated?
Mariel

**Comment by Jegelewicz** [comment]
OK, we can stick with premolar tooth, but fang is needed as it is a tooth specific to snakes (not another version of canine).  Sometimes the specimen is only a tooth, so for ES it is very helpful to have the different tooth types.  Thanks!

**Comment by campmlc** [comment]
Well, unicuspids are shrew premolars, so if you decide it is useful let me
know. I just want to make sure there is some discussion before creating
parts that might be redundant.
