### ISSUE TITLE
update the label on several (1,500+) positions

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#929]
I need to update the label on several (1,500+) positions so using the bulkloader. Since they are positions I cannot do that. Can you make it happen?

[2016_08_ChangeContainer (1).xlsx](https://github.com/ArctosDB/arctos/files/459760/2016_08_ChangeContainer.1.xlsx)

**Comment by dustymc** [comment]
Please advise re: 14 not-positions:

UAM@ARCTOS> select barcode,container_type from container where container_type != 'position' and barcode in (select barcode from dlm.my_temp_cf);

BARCODE
------------------------------------------------------------------------------------------------------------------------
CONTAINER_TYPE
------------------------------------------------------------
396828
cryovial

396829
cryovial

396830
cryovial

396831
cryovial

396832
cryovial

396833
cryovial

396834
cryovial

396835
cryovial

396836
cryovial

396837
cryovial

396838
cryovial

396839
cryovial

396840
cryovial

396841
cryovial


14 rows selected.
