### ISSUE TITLE
Borrows from non-Arctos institutions

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#930]
I am looking for guidance on some borrowed specimens that we received recently from a non-Arctos institution.  I created a borrow to help me keep track of the loan, but how can I store the details (the list of specimens)?  I'd like to scan the loan document and attach it to the borrow.  Has anyone already developed a solution for this?  Thanks!

**Comment by dustymc** [comment]
I'll add a "documents borrow" Media relationship and handlers, and a media widget to borrows.

Until then, copy/pasting into "nature of transaction" seems to be the usual approach.
