### ISSUE TITLE
customize data entry

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#937]
turning things on/off isn't working - see depth units msg from dmns

**Comment by campmlc** [comment]
I'm getting depth units errors trying to bulkload fish data - same issue?

**Comment by dustymc** [comment]
Cannot re-create - customize form is working for me, closing issue.

Mariel - probably not the same thing, file a new Issue.

**Comment by dustymc** [comment]
Reopening - @sharpphyl, what browser/OS, anything interesting in the javascript console, ???? Anything that might help me figure out why this works for me and not you GREATLY appreciated.

**Comment by sharpphyl** [comment]
Dusty,

Do these two screens help at all?

Am I making any error when I try to customize the form?  Most everything
else seems to work ok.

Phyllis

[image: Inline image 1]

[image: Inline image 2]

**Comment by dustymc** [comment]
Yep, that did it, thanks. I'll get it patched in hopefully tonight.
