### ISSUE TITLE
New collection type

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#941]
I have some specimens from the University of Mississippi.  Should we create a new Other_ID-Type for them or should I use "institutional catalog number".

**Comment by dustymc** [comment]
If all you know is UoM and/or have some obscure identifier, something generic may be good enough - that sort of thing probably won't ever be resolvable. If you know eg, UoM mammal collection and have their catalog number (or something similar), I would recommend a new type of ID so we can just add base_url to the code table and talk to them when/if they come online.
