### ISSUE TITLE
Accession Bulkloader

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#942]
The accession bulkloader worked for me in the past, but now I'm having difficulty.  I keep getting this error:
![capture](https://cloud.githubusercontent.com/assets/5725767/19208828/af3e2ffc-8cbc-11e6-9fad-1d98c3b0b7c1.JPG)
I've tried changing the numerical values in my accession number and checking all of my dates.  I don't know where else to look for the problem.  I am unable to attach my data file here.

**Comment by dustymc** [comment]
Check IS_PUBLIC_FG - values 1 (=yes) or 0 (no) should work.

**Comment by Jegelewicz** [comment]
Dusty, you're the man!  That worked.
