### ISSUE TITLE
better protect CFC

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#943]
some probes to /component - how to better protect that dir while keeping webservices happy?

**Comment by dustymc** [comment]
elevating - recent attack did hit some cfcs

**Comment by mkoo** [comment]
are there CF consultants or specialists you can consult?

**Comment by dustymc** [comment]
No I don't think I need technical help, it's just a matter of checking how CFCs are used==>how they can be best secured. CF has some tools/settings, but they're really aimed at CFCs made for CF while I mostly use other languages so not terribly useful.

To be clear I don't think it's possible to do anything very dangerous via CFC - database access rules prevent that - but it's definitely possible to be annoying, and to use them in things like DDOS attacks, and that sort of thing seems to be increasingly common. I'm just adding a layer that can help mitigate.

And of course I'm working without a test environment, and these almost by definition are used in complex ways, so I'm trying to be careful=slow and not break anything. That works about like you might expect - I think I've only (briefly!) exploded everything three times so far....

**Comment by dustymc** [comment]
done
