### ISSUE TITLE
add Higher Geography

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#946]
Please add Africa, Madagascar to Higher Geography.  We have specimens from Nosy Be, a different island off the coast of Madagascar Island.  Thx.

**Comment by mkoo** [comment]
HI Sharpphyl (Sorry I dont know who this is), if no one added in Nosy Be, I
can for you.
MK

**Comment by mkoo** [comment]
Sharpphyl, it's already been created (perhaps someone responded already) so
am closing.

http://arctos.database.museum/Locality.cfm?Action=editGeog&geog_auth_rec_id=10007082

thanks,MK

**Comment by dustymc** [comment]
Done, cleaned up, and I created Africa, Madagascar, Diana, Nosy Be for the island.

**Comment by mkoo** [comment]
that explains why nothing more needed to be done!

**Comment by sharpphyl** [comment]
Ok, now do you want to create Northern Samar as a province in the PHilippines - see https://en.wikipedia.org/wiki/Northern_Samar.  Thx

**Comment by dustymc** [comment]
Done. @mkoo , do you have access to anyone familiar with Philippines admin divisions? Should we be using regions as state and provinces as county?? https://en.wikipedia.org/wiki/Administrative_divisions_of_the_Philippines

**Comment by mkoo** [comment]
yeah its confusing for PH

GADM (http://www.gadm.org/) lists the provinces as primary division so
would be equivalent to State. The regions are not necessarily spatially
aligned but more or less cluster provinces by island, however there are
extralimital ones and independent ones to make it more fun. The secondary
division would be the municipalities. And third are the Barangays. I
georeferenced PHilippine localities for over a year and drove several
assistants to the brink of sanity. (I have never seen them again...)
