### ISSUE TITLE
Data entry

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#950]
Is this a bug or operator error?  After entering lat/long coordinates for a lot (see DMNS:Inv:21759) an error is reported if I don't enter lat/long coordinates for the next entries.

![error message](https://cloud.githubusercontent.com/assets/15368365/19389302/c1a6cef0-91e0-11e6-91c2-fa3cf358efbd.png)

![next entry without coordinates](https://cloud.githubusercontent.com/assets/15368365/19389333/dfcb95e6-91e0-11e6-9f74-768b696aa84a.png)

Note that the screen is blue indicating that the entry has no errors but it's still rejected.

Thanks!

**Comment by sharpphyl** [comment]
As an update, this error has spread to all the entries in the bulk upload under my name.  These entries do not have coordinates but followed entries that did have coordinates.  

![bulk upload error 18 oct 2016](https://cloud.githubusercontent.com/assets/15368365/19482377/2d1ae088-950e-11e6-95aa-3d8d1d22fc48.JPG)

**Comment by sharpphyl** [comment]
I was able to clean these out through bulk loader so there's less urgency for me unless others are having a similar issue.

**Comment by dustymc** [comment]
Cannot re-create; re-open (and preserve test data) if this happens again.
