### ISSUE TITLE
Delete Tridacna crocca

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#953]
Unless someone is using this taxon, it's a mispelling of Tridacna crocea and can be deleted.

http://www.marinespecies.org/aphia.php?p=taxdetails&id=207673

**Comment by dustymc** [comment]
That is at least a very common mistake - https://www.google.com/search?q=Tridacna+crocca&ie=utf-8&oe=utf-8#q=Tridacna+crocca&nfpr=1 

Common mistakes are useful for discovery, so I'm hesitant to delete it. I added a "synonym of" relationship.

(And I use "synonym" to mean "someone's spelt it thataway" with no "code" implications - we should probably have stricter definitions. See also #735.)

**Comment by sharpphyl** [comment]
Well, taxonomically it's not a synonym, but I'll agree that it might be a
search term.

Here's another that Andres had in his collection but has now corrected:
Hippopus hippopuss instead of Hippopus hippopus.  It shows up on a Google
search because it's referencing the UAM entry that he's corrected.

I don't want our volunteers to make a typo and have the misspelled version
be accepted.  If Tridanca crocca is a synonym, will it signal that it isn't
the accepted term?

**Comment by dustymc** [comment]
My working definition of Arctos taxonomy is "things people have thought were 'taxonomy'." Certainly nobody's idea of "correct," but it seems to be more useful than anything else we've tried...

It looks like many people have used Tridacna crocca for whatever reason, so it's "taxonomy-ish" enough for me! (Eg it's useful, even if it is not and has never been "code compliant" or whatever.)

Google only finds Hippopus hippopuss that originate from Arctos, so I would agree with just deleting that before it has a chance to propagate. (It's used in one specimen, I'm re-opening this until I can deal with that.)

See https://github.com/ArctosDB/arctos/issues/756 - the need is documented, but I don't know that we have a workable solution to "preferred by." Well-defined relationships (http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXON_RELATION) may be a necessary precursor.

**Comment by sharpphyl** [comment]
Yes, the "preferred" or "accepted" synonym designation would be helpful for us.  Glad to see the issue is already open.
