### ISSUE TITLE
Please add Uthai Thani Province, Thailand to Higher Geography

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#954]
https://en.wikipedia.org/wiki/Uthai_Thani_Province

Thx.

Phyllis

**Comment by sharpphyl** [comment]
Please also add Anosy Region, Madagascar.  See https://en.wikipedia.org/wiki/Anosy_Region

**Comment by sharpphyl** [comment]
Done.  Whew!

**Comment by mkoo** [comment]
Yay! and closing....
