### ISSUE TITLE
Request for way to request new locality within Arctos

### ISSUE THREAD

**Issue by bjohnson-dmns** [ArctosDB/arctos#957]
As we understand the process currently, to have a new higher geography created, we should submit a GitHub request here in the Issues section.  I fear we will overwhelm this forum with our requests.  Is there a way that a form could be created within Arctos that would let users request new localities be created within Arctos.  I am envisioning a form that looks exactly like the Higher Geo search, but user can fill in fields as needed and then hit submit.  Ideally there would also be some mechanism to alert user when request is completed.  We have a dozen or so users processing a 18,000+ donation that spans the world and includes a ton of mostly marine locations (islands, coastal provinces, etc) and it appears a ton of the localities are not created in Arctos' Higher Geo.  A form within Arctos would make it a lot easier for our users (and everyone else) to request Geo be added and also keep Geo Creation requests from overwhelming the Issues forum on GitHub.

We are open to other solutions as well, we are just worried that all our requests will reduce the visibility of other important issues in the forum that get lost in all the Geo Requests.

Thank you.

Bryan

**Comment by dustymc** [comment]
Granted admin access; this may be worth revisiting in the future, but closing for now.
