### ISSUE TITLE
Enable truncation of higher geography

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#958]
Currently, we can't select a higher level of higher geography.  It seems like this should already be an existing higher geography because it is included in a lower level but we cannot select it.  

For example:  We need Asia, Russia, Sea of Okhotsk.    

The options available both associate a specific  island with the Sea.  We don't want a specific island but can't choose Asia, Sea of Okhotsk, Russia even though those are the first three elements in the chain.
![sea of okhotsk issue](https://cloud.githubusercontent.com/assets/15368365/19489511/c2f9a778-9528-11e6-9a95-930836592d18.JPG)

**Comment by dustymc** [comment]
I'm flagging wontfix, but feel free to re-open - there's plenty of room for further discussion!

I think you're asking for some sort of "create the child as it's own entity" automation. I'm reluctant to go there; I'm not sure the data support such automation, I'm not sure we want to unnecessarily propagate our arbitrary mix of political and geographical data, and I'm not sure we want to provide data entry personnel with lots of ambiguous choices (eg, several higher_geog entries which lie under one point) without individual consideration.

For example, all of Hawaii Island is in Hawaii County so (as long as we're providing "physical" and political names) it doesn't make sense to have a Hawaii Island that's NOT in the county. Midway is a Hawaiian island that's not in the state of Hawaii. (Maybe that's only important when going "upstream"??) Etc., etc., etc. I think unraveling those types of data would be extremely difficult to script without introducing extraneous or erroneous values.
