### ISSUE TITLE
default ID/taxonomy specimensearch

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#965]
From @DerekSikes 

> The most common mistake I find people make when they search Arctos is to put a higher taxon, like a family name, into the 'Identification' field and think they're searching Arctos for all records that belong to that family.
> 
> Instead they are actually searching for all records that are identified as that family (but not lower). This leads them to believe we have no specimens identified below family level, then they email me and I have to explain that they need to expand the search box, find the family field and search that.
> 
> What about switching the default first-seen search box from 'Identification' to 'Taxon name' because the latter would behave the way most people think such a search term should behave. It seems like a better field if someone had access to only one field to search.
> 
> Another solution would be to make the default display of that search box section be expanded (include all search options) so people would have to click 'show fewer options' to change the default - and this way they would by default at least SEE that there are other fields they might try out. Explaining all this to so many different people gets tiring.

I'm up for anything and have no real opinion. 

The "taxon name" box is a little slow (#735) and returns what some would likely consider false positives. The taxon name option also doesn't QUITE line up with "identified as that family." When you ID a specimen as Neotoma you are implicitly asserting family=Cricetidae (because http://arctos.database.museum/name/neotoma#Arctos), while searching the "taxon name" for Muridae will find Neotoma (because http://arctos.database.museum/name/neotoma#CatalogueofLife). You'd have to scroll down to the "family" search term (which only considers your preferred classification) to REALLY get "identified as that family."

I'm slightly hesitant to add to the default visible fields because we get a lot of complaints about the form being too complicated, but we got those when it was 6 fields too.

And unrelated but while we're here, can we get rid of anything in the default Identifiers pane?

<img width="704" alt="screen shot 2016-10-27 at 4 58 40 pm" src="https://cloud.githubusercontent.com/assets/5720791/19789690/b5b9f172-9c66-11e6-8494-83eaac0c8362.png">

**Comment by campmlc** [comment]
I strongly agree with Derek about changing the default to Taxon name. Much
better for people to pick up a bunch of things, some of which they may not
want, than nothing. We need to make it easier to find things in Arctos, and
this is a good first step.

On that same topic, GUID should only show up for experienced users. No need
for teachers or general public to see that as default.

**Comment by jtgiermakowski** [comment]
I'm of the similar opinion:

Based on my experience, Taxon Name and Common Name ought to be the
default Identification and Taxonomy fields. False positives are good in
this instance.

As far as the Identification, GUID is too technical and already 'included'
in the "Any Identifier" search box. Use "Collection" "Catalog Number" "Any
Identifier"

saludos, Tom

**Comment by dustymc** [comment]
Add "=term" functionality to taxon name, individual ranked term searches

**Comment by dustymc** [comment]
previously fixed
