### ISSUE TITLE
Add 'Uses Media' option to Project Search page

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#970]
Currently Project Type options are a dropdown menu of 5 choices which would be made more useful if we could filter those project type selections to projects with associated media. I have had need to find Project Type = "Neither uses nor contributes specimens" with photos only, as well as projects that "Contributes specimens" and have media. Maybe add a checkbox to limit to projects with media when searching?

**Comment by dustymc** [comment]
done for v7.4++
