### ISSUE TITLE
Bulk uploading barcodes to parts

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#973]
I'd like to request a tool to bulk upload barcodes to existing parts, without using the parts bulkloader.  The problem with the parts bulkloader is that condition and disposition are required. This makes sense for new parts, but for existing parts it is very difficult to extract all this information from the current Arctos specimen  results download (concatenated parts column) and then rematch it to the records for upload.
I am going to have to load (tens, hundreds . . ) of thousands of parts into new barcodes this way, so a new tool would be very helpful. 
A more tricky issue is that with the existing form, if there is a single problem with the parts upload, none of the parts will load. It would be so much better if the parts without problems could load, leaving us with just the problem records to sort through and fix.  It is very difficult to figure out which of several hundred parts contains the problem that triggers the Oracle error.

**Comment by KyndallH** [comment]
Try Parts>>>Container under the batch tools for this. I think that is exactly what you are asking for.

http://arctos.database.museum/tools/BulkloadPartContainer.cfm

**Comment by campmlc** [comment]
Yes, thanks - that looks exactly like what I need. Thank you, Kyndall!

**Comment by dustymc** [comment]
> a tool to bulk upload barcodes

Possibly unrelated, how are the barcode and the part coming together in "meatspace" - perhaps there's something procedural that could simplify/etc. this.

> if there is a single problem with the parts upload, none of the parts will load. It would be so much better if the parts without problems could load

Single problems are often/usually indicative of systemic problems. "It didn't really work but we did some random stuff anyway" is not something I'm comfortable building. I could possible do a more thorough pre-check to get better errors - what specifically isn't being caught before the load process?

**Comment by campmlc** [comment]
This issue relates to our project to barcode legacy cryovials. We are
currently using Object+Barcode->Container to add one part to one barcode at
a time for one test freezer, but it is extremely time consuming. I'm trying
to come up with a more efficient method, that hopefully will not introduce
additional errors.  I'll try Kyndall's suggestion first. I am a bit worried
about error identification and management given how many samples I will
need to load.

**Comment by dustymc** [comment]
I'd need to know some more details, but on the surface that sounds like a great place for a custom app. I think you're right to worry about problems - if you're coming from where I think you are those data were mostly uncontrolled and have lots of easy-to-find inconsistencies, which generally means lots more problems as you get closer in. Dealing with those as they're found is likely a worthwhile goal. Apps to do very specific repetitive things (eg, find the stuff associated with an NK#, scan barcode) are generally quick and easy to build.

**Comment by campmlc** [comment]
Great - maybe we can Skype or equivalent? I'll try to put together some
documentation so you can see what we are dealing with.
