### ISSUE TITLE
ID Type

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#974]
Can we add an Id Type "Bernardino Rivadavia Natural Sciences Museum"?

**Comment by dustymc** [comment]
Do they have a semi-official acronym so we can maintain the pattern of eg "BMNH: Bell Museum of Natural History"? (http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_OTHER_ID_TYPE for more examples.)

What is the description/definition?

Is there a base URL (onto which the ID value can be appended to produce a link), and if so what is it?

**Comment by Jegelewicz** [comment]
They do have acronyms, but it appears there are several - see http://www.macn.secyt.gov.ar/investigacion/inv_colecciones-macn.php
I am adding some herbarium sheets that came from them in an exchange and that code appears to be BA-V.

Not sure how you want to handle this...

**Comment by dustymc** [comment]
The "BA-V" series looks like it could become resolvable, so if you know (suspect? strongly suspect??) that, it's certainly preferable from a data usability perspective.

If we can't narrow it down to a collection, the ID cannot possibly become resolvable - "WHATEVER:1" might refer to a plant or mammal or ... 

From the page you linked, looks like the "institution" (=non-resolvable trashcan-o-identifiers) should be MACN:  Museo Argentino de Ciencias Naturales and the vascular plant collection (=potentially-realistic hope of finding the one correct specimen) something like BA-V: Museo Argentino de Ciencias Naturales Plantas Vasculares Colección (which fits into the code table with 3 characters to spare!). 

But from your initial comment I'm guessing neither of those line up very well with what's on the specimens, and that's never preferable....

????????????????????

Lacking better ideas (@ccicero ??) I'm happy to enter whatever you want in the code table - just be as specific as you can and include a verbose definition, please!

**Comment by Jegelewicz** [comment]
I am just looking at data - give me a bit to pull the sheet and then perhaps I can give you a better answer.
