### ISSUE TITLE
ES part name

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#979]
Can we add cannon to the ES parts?

**Comment by dustymc** [comment]
metatarsal?

**Comment by Jegelewicz** [comment]
I can do that - just thinking we might end up with other horses....I don't really have a preference.

**Comment by dustymc** [comment]
My preference is mainly for consistency.

Whatever is done should work across collections - I-the-user don't care where it's cataloged etc, I just want ankle-bones! UAM:ES has ~140 horse metatarsals (http://arctos.database.museum/SpecimenResults.cfm?collection_id=21&part_name=metatarsal&scientific_name=Equus) - I suggest either doing what they've done, or coordinating something better with them.

(And another 120 metacarpals - are those "cannon bones" too?)

Also seems useful to eg, find moose and caribou for comparison, and I think having to switch part vocabulary to do so would throw off at least some users.

So I lean towards 'metatarsal,' but if some curator/user/etc. has some compelling reason to do something else (here or anywhere else) I'm completely willing to discuss it.
