### ISSUE TITLE
object tracking results display

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#982]
There seem to be a problem with the result display in object tracking when double click is used to expand a container. I lose the right Edit panel, and only some of the results are visible. It is not possible to scroll down and see the remaining results. The two screenshots attached show before and after double click on MSB DGR (room).
![screenshot 2016-11-15 14 01 38](https://cloud.githubusercontent.com/assets/14808196/20324139/9a7119ce-ab3c-11e6-9afe-7de8aa4d5515.png)
![screenshot 2016-11-15 14 02 36](https://cloud.githubusercontent.com/assets/14808196/20324140/9a71ec64-ab3c-11e6-9653-d4ea6691fe16.png)

**Comment by dustymc** [comment]
I think that's just your browser trying to make use of screen real estate, which is stretched out by (at least) ...

<img width="1165" alt="screen shot 2016-11-15 at 1 25 51 pm" src="https://cloud.githubusercontent.com/assets/5720791/20324904/362e2f7e-ab37-11e6-901b-0a6685395805.png">

Obvious options include finding another tree-viewer library, limiting the size of container labels, or changing what's displayed.

**Comment by campmlc** [comment]
OK, I zoomed out of my screen and could see the rest. I fixed the overly
long slide box label, part of an ongoing student inventory project. Do we
have a way to search for all slide boxes in DGR? This is what I needed to
edit when I ran into the display problems. I need to pull up all slide
boxes contained in container barcode = DGR.

**Comment by dustymc** [comment]
>all slide boxes in DGR

select barcode,label,container_id from container where container_type='slide box' and parent_container_id=(select container_id from container where barcode='DGR');

[temp_dgrchild.csv.zip](https://github.com/ArctosDB/arctos/files/593303/temp_dgrchild.csv.zip)

**Comment by campmlc** [comment]
Thanks. Can we add this type of query option to the existing Find
Containers Search Tool?

**Comment by dustymc** [comment]
Unaddressed parts of this moved to #986, closing
