### ISSUE TITLE
taxonomy relationships

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#983]
Problems:

- "any taxonomy" search does not perform very well because it must scan
    - taxon_term (~120M rows)
    - taxon term for each related taxon (same ~120M rows)
    - taxon term for each inversely-related taxon (same ~120M rows, yet again)
- Arctos relationships (name<-->name) and GlobalNames relationships (assertions via classifications) are structured differently (and we have no control over what we get from GlobalNames)

Proposal:

When a relationship is created/altered, trigger-create (and maintain) relevant classifications.

Impact:

Our (display) data and GlobalNames' would be compatible; users would need to look in only one place to find all "relationships" (presented as alternate classifications). "Any taxon" searches would just need to scan taxon term one time; all related info would be embedded.

First-pass details:

The trigger would "own" a classification ("Arctos Relationships" perhaps). onChange to taxon relations, the trigger would grab "our" related classifications (those controlled by http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXONOMY_SOURCE) and insert them into the related records. No user behavior or form changes would be necessary.

Potential future improvement:

Be more precise. Make relationships explicitly between classifications, instead of names (propagated to "our" classifications). I can't yet grasp the details of how that might work, so I'm suggesting an incremental approach. Minimally, we'd need to pick classifications instead of names when creating relationships, and somehow deal with the somewhat volatile nature of classifications. (It's often easier to delete and re-make a classification than to alter an existing one - the classification loader is doing so for ~250K classifications as I type this - reconciling that with "permanent" relationships would take some thought and development.)

Example (from current data):

This relationship:

<img width="510" alt="screen shot 2016-11-18 at 11 26 40 am" src="https://cloud.githubusercontent.com/assets/5720791/20443506/eb6bb798-ad81-11e6-97d8-eb51e9941130.png">

Would insert a copy of this classification:

<img width="706" alt="screen shot 2016-11-18 at 11 27 09 am" src="https://cloud.githubusercontent.com/assets/5720791/20443517/f9c20612-ad81-11e6-9359-a7319db841c9.png">

changed from "Arctos" to "Arctos Relationships" into http://arctos.database.museum/name/Myodes, and a copy of this classification:

<img width="669" alt="screen shot 2016-11-18 at 11 27 50 am" src="https://cloud.githubusercontent.com/assets/5720791/20443534/1134ff5c-ad82-11e6-9854-847c83777cb1.png">

changed from "Arctos" to "Arctos Relationships" into http://arctos.database.museum/name/Clethrionomys

Searches for "Myodes" would then find "Clethrionomys" (and the inverse, and from there specimens using either taxon) by way of only the classifications.

("Myodes" will currently find Clethrionomys because http://arctos.database.museum/name/Clethrionomys#InterimRegisterofMarineandNonmarineGenera includes Myodes; Clethrionomys will currently NOT find Myodes from classification data because no classification on http://arctos.database.museum/name/Myodes contains the string "Clethrionomys.")

If accepted, this Issue should also solve

- #758 (by getting all related information in the same place)
- #735 (this is a path to the "possible improvement"); vocabulary issues remain for various other reasons
- #965 (by eliminating most of the slow queries)

It would be possible under this model to be explicit about WHY a Clethrionomys classification exists on the Myodes page ("Clethrionomys is a junior synonym of Myodes" as some sort of non-classification taxon term or similar), but the reciprocal vocabulary issues in #735 probably need sorted out before we go there.

Thoughts?

**Comment by Jegelewicz** [comment]
Closing for consolidation with #1136
