### ISSUE TITLE
Add part and fields

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#989]
Please add "fossil" to the part names for Invertebrates.

How to we get the fields (seen in other entries) for System/Period, Formation and Stage/Age.  I don't see them in the options for customizing the data entry form.

**Comment by dustymc** [comment]
I think "fossil" is a condition (or something of the sort), not a part - WHAT is fossilized?

Geology attributes are currently tied to collection type ES for data entry, and I doubt all Inv collections want to see them.

If you have a few, you might just add them via edit locality - geology is always available there. Otherwise let me know and I'll figure out how to make that available in data entry by collection.

**Comment by sharpphyl** [comment]
I see quite a few entries in Arctos with just "fossil" but we agree with your concern.

Can we add "shell (fossil)" as a Part Name for Inverts?  That will allow us to add other parts (corals, tests, etc.) as fossils as we catalog them.

We do not have a lot of fossils so far, so we can add the geology to the locality for now.  If our collection grows, we'll address the issue then.

**Comment by dustymc** [comment]
Ugh - fish...

I'll try to clean that up - thanks!

My preference would be to deal with the "fossil" bit elsewhere (but I have no idea where that might be) - if that's a part, then I have to search two things to find fossil shells in your collection and in the paleo collections (where they're just "shell"), which should be avoided if at all possible.

There also seems to be no "official" definition of "fossil," and I always dislike vague terminology. http://arctos.database.museum/guid/UAM:Mamm:53942 was made into stew, for example - is that a "fossil"? (I think the only real answer is "depends who you ask.")

That said, I'm happy enough to do whatever the AWG (and you, and perhaps the paleo folks) decide on, and recovering "shell (fossil)" into a better place (should we find one) should be straightforward - I think it's safe to run with that and (potentially) sort it out later if this is holding you up.

**Comment by sharpphyl** [comment]
We're a small part of the fossil world, so if Paleo has a different approach, we'll certainly go along.  Thanks for doing "shell (fossil)" for now.  We can always shift to a better place as we won't have that many entries.

**Comment by dustymc** [comment]
I added shell (fossil) and opened #991
