### ISSUE TITLE
Media CSV

### ISSUE THREAD

**Issue by cfidler** [ArctosDB/arctos#994]
The media export csv file concatenates all relationships into one column. It does the same thing for labels. Would it be possible for values to have their own columns? The data would be much more useful if the values were parsed out. - Thanks, Christina

**Comment by dustymc** [comment]
Anything's possible, but...

1) No two downloads would ever be the same, which I suspect would make doing anything predictable with them difficult, and
2) Some downloads would contain a lot of columns - there are a few Media with a couple hundred relationships, and
3) It would not be "valid" CSV (or not have easy-to-understand headers if we somehow made them unique) when eg, there are multiple labels of the same type.

Stuffing relational data into flat data structures always come with compromises. Arctos could provide non-flat download (JSON arrays or such), but unwinding that is probably not all that different than unwinding the concatenated columns.

**Comment by dustymc** [comment]
Its JSON now.
